// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/scalapb/scalapb.proto

package scalapb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Whether to apply the options only to this file, or for the entire package (and its subpackages)
type ScalaPbOptions_OptionsScope int32

const (
	// Apply the options for this file only (default)
	ScalaPbOptions_FILE ScalaPbOptions_OptionsScope = 0
	// Apply the options for the entire package and its subpackages.
	ScalaPbOptions_PACKAGE ScalaPbOptions_OptionsScope = 1
)

var ScalaPbOptions_OptionsScope_name = map[int32]string{
	0: "FILE",
	1: "PACKAGE",
}

var ScalaPbOptions_OptionsScope_value = map[string]int32{
	"FILE":    0,
	"PACKAGE": 1,
}

func (x ScalaPbOptions_OptionsScope) Enum() *ScalaPbOptions_OptionsScope {
	p := new(ScalaPbOptions_OptionsScope)
	*p = x
	return p
}

func (x ScalaPbOptions_OptionsScope) String() string {
	return proto.EnumName(ScalaPbOptions_OptionsScope_name, int32(x))
}

func (x *ScalaPbOptions_OptionsScope) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ScalaPbOptions_OptionsScope_value, data, "ScalaPbOptions_OptionsScope")
	if err != nil {
		return err
	}
	*x = ScalaPbOptions_OptionsScope(value)
	return nil
}

func (ScalaPbOptions_OptionsScope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{0, 0}
}

// Naming convention for generated enum values
type ScalaPbOptions_EnumValueNaming int32

const (
	ScalaPbOptions_AS_IN_PROTO ScalaPbOptions_EnumValueNaming = 0
	ScalaPbOptions_CAMEL_CASE  ScalaPbOptions_EnumValueNaming = 1
)

var ScalaPbOptions_EnumValueNaming_name = map[int32]string{
	0: "AS_IN_PROTO",
	1: "CAMEL_CASE",
}

var ScalaPbOptions_EnumValueNaming_value = map[string]int32{
	"AS_IN_PROTO": 0,
	"CAMEL_CASE":  1,
}

func (x ScalaPbOptions_EnumValueNaming) Enum() *ScalaPbOptions_EnumValueNaming {
	p := new(ScalaPbOptions_EnumValueNaming)
	*p = x
	return p
}

func (x ScalaPbOptions_EnumValueNaming) String() string {
	return proto.EnumName(ScalaPbOptions_EnumValueNaming_name, int32(x))
}

func (x *ScalaPbOptions_EnumValueNaming) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ScalaPbOptions_EnumValueNaming_value, data, "ScalaPbOptions_EnumValueNaming")
	if err != nil {
		return err
	}
	*x = ScalaPbOptions_EnumValueNaming(value)
	return nil
}

func (ScalaPbOptions_EnumValueNaming) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{0, 1}
}

type ScalaPbOptions struct {
	// If set then it overrides the java_package and package.
	PackageName *string `protobuf:"bytes,1,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	// If true, the compiler does not append the proto base file name
	// into the generated package name. If false (the default), the
	// generated scala package name is the package_name.basename where
	// basename is the proto file name without the .proto extension.
	FlatPackage *bool `protobuf:"varint,2,opt,name=flat_package,json=flatPackage" json:"flat_package,omitempty"`
	// Adds the following imports at the top of the file (this is meant
	// to provide implicit TypeMappers)
	Import []string `protobuf:"bytes,3,rep,name=import" json:"import,omitempty"`
	// Text to add to the generated scala file.  This can be used only
	// when single_file is true.
	Preamble []string `protobuf:"bytes,4,rep,name=preamble" json:"preamble,omitempty"`
	// If true, all messages and enums (but not services) will be written
	// to a single Scala file.
	SingleFile *bool `protobuf:"varint,5,opt,name=single_file,json=singleFile" json:"single_file,omitempty"`
	// By default, wrappers defined at
	// https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto,
	// are mapped to an Option[T] where T is a primitive type. When this field
	// is set to true, we do not perform this transformation.
	NoPrimitiveWrappers *bool `protobuf:"varint,7,opt,name=no_primitive_wrappers,json=noPrimitiveWrappers" json:"no_primitive_wrappers,omitempty"`
	// DEPRECATED. In ScalaPB <= 0.5.47, it was necessary to explicitly enable
	// primitive_wrappers. This field remains here for backwards compatibility,
	// but it has no effect on generated code. It is an error to set both
	// `primitive_wrappers` and `no_primitive_wrappers`.
	PrimitiveWrappers *bool `protobuf:"varint,6,opt,name=primitive_wrappers,json=primitiveWrappers" json:"primitive_wrappers,omitempty"`
	// Scala type to be used for repeated fields. If unspecified,
	// `scala.collection.Seq` will be used.
	CollectionType *string `protobuf:"bytes,8,opt,name=collection_type,json=collectionType" json:"collection_type,omitempty"`
	// If set to true, all generated messages in this file will preserve unknown
	// fields.
	PreserveUnknownFields *bool `protobuf:"varint,9,opt,name=preserve_unknown_fields,json=preserveUnknownFields,def=1" json:"preserve_unknown_fields,omitempty"`
	// If defined, sets the name of the file-level object that would be generated. This
	// object extends `GeneratedFileObject` and contains descriptors, and list of message
	// and enum companions.
	ObjectName *string `protobuf:"bytes,10,opt,name=object_name,json=objectName" json:"object_name,omitempty"`
	// Experimental: scope to apply the given options.
	Scope *ScalaPbOptions_OptionsScope `protobuf:"varint,11,opt,name=scope,enum=scalapb.ScalaPbOptions_OptionsScope" json:"scope,omitempty"`
	// If true, lenses will be generated.
	Lenses *bool `protobuf:"varint,12,opt,name=lenses,def=1" json:"lenses,omitempty"`
	// If true, then source-code info information will be included in the
	// generated code - normally the source code info is cleared out to reduce
	// code size.  The source code info is useful for extracting source code
	// location from the descriptors as well as comments.
	RetainSourceCodeInfo *bool `protobuf:"varint,13,opt,name=retain_source_code_info,json=retainSourceCodeInfo" json:"retain_source_code_info,omitempty"`
	// Scala type to be used for maps. If unspecified,
	// `scala.collection.immutable.Map` will be used.
	MapType *string `protobuf:"bytes,14,opt,name=map_type,json=mapType" json:"map_type,omitempty"`
	// If true, no default values will be generated in message constructors.
	NoDefaultValuesInConstructor *bool                           `protobuf:"varint,15,opt,name=no_default_values_in_constructor,json=noDefaultValuesInConstructor" json:"no_default_values_in_constructor,omitempty"`
	EnumValueNaming              *ScalaPbOptions_EnumValueNaming `protobuf:"varint,16,opt,name=enum_value_naming,json=enumValueNaming,enum=scalapb.ScalaPbOptions_EnumValueNaming" json:"enum_value_naming,omitempty"`
	// Indicate if prefix (enum name + optional underscore) should be removed in scala code
	// Strip is applied before enum value naming changes.
	EnumStripPrefix *bool `protobuf:"varint,17,opt,name=enum_strip_prefix,json=enumStripPrefix,def=0" json:"enum_strip_prefix,omitempty"`
	// Scala type to use for bytes fields.
	BytesType *string `protobuf:"bytes,21,opt,name=bytes_type,json=bytesType" json:"bytes_type,omitempty"`
	// Enable java conversions for this file.
	JavaConversions *bool `protobuf:"varint,23,opt,name=java_conversions,json=javaConversions" json:"java_conversions,omitempty"`
	// List of message options to apply to some messages.
	AuxMessageOptions []*ScalaPbOptions_AuxMessageOptions `protobuf:"bytes,18,rep,name=aux_message_options,json=auxMessageOptions" json:"aux_message_options,omitempty"`
	// List of message options to apply to some fields.
	AuxFieldOptions []*ScalaPbOptions_AuxFieldOptions `protobuf:"bytes,19,rep,name=aux_field_options,json=auxFieldOptions" json:"aux_field_options,omitempty"`
	// List of message options to apply to some enums.
	AuxEnumOptions []*ScalaPbOptions_AuxEnumOptions `protobuf:"bytes,20,rep,name=aux_enum_options,json=auxEnumOptions" json:"aux_enum_options,omitempty"`
	// List of enum value options to apply to some enum values.
	AuxEnumValueOptions []*ScalaPbOptions_AuxEnumValueOptions `protobuf:"bytes,22,rep,name=aux_enum_value_options,json=auxEnumValueOptions" json:"aux_enum_value_options,omitempty"`
	// For use in tests only. Inhibit Java conversions even when when generator parameters
	// request for it.
	TestOnlyNoJavaConversions    *bool    `protobuf:"varint,1001,opt,name=test_only_no_java_conversions,json=testOnlyNoJavaConversions" json:"test_only_no_java_conversions,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *ScalaPbOptions) Reset()         { *m = ScalaPbOptions{} }
func (m *ScalaPbOptions) String() string { return proto.CompactTextString(m) }
func (*ScalaPbOptions) ProtoMessage()    {}
func (*ScalaPbOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{0}
}

var extRange_ScalaPbOptions = []proto.ExtensionRange{
	{Start: 10000, End: 536870911},
}

func (*ScalaPbOptions) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ScalaPbOptions
}

func (m *ScalaPbOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalaPbOptions.Unmarshal(m, b)
}
func (m *ScalaPbOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalaPbOptions.Marshal(b, m, deterministic)
}
func (m *ScalaPbOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalaPbOptions.Merge(m, src)
}
func (m *ScalaPbOptions) XXX_Size() int {
	return xxx_messageInfo_ScalaPbOptions.Size(m)
}
func (m *ScalaPbOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalaPbOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ScalaPbOptions proto.InternalMessageInfo

const Default_ScalaPbOptions_PreserveUnknownFields bool = true
const Default_ScalaPbOptions_Lenses bool = true
const Default_ScalaPbOptions_EnumStripPrefix bool = false

func (m *ScalaPbOptions) GetPackageName() string {
	if m != nil && m.PackageName != nil {
		return *m.PackageName
	}
	return ""
}

func (m *ScalaPbOptions) GetFlatPackage() bool {
	if m != nil && m.FlatPackage != nil {
		return *m.FlatPackage
	}
	return false
}

func (m *ScalaPbOptions) GetImport() []string {
	if m != nil {
		return m.Import
	}
	return nil
}

func (m *ScalaPbOptions) GetPreamble() []string {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *ScalaPbOptions) GetSingleFile() bool {
	if m != nil && m.SingleFile != nil {
		return *m.SingleFile
	}
	return false
}

func (m *ScalaPbOptions) GetNoPrimitiveWrappers() bool {
	if m != nil && m.NoPrimitiveWrappers != nil {
		return *m.NoPrimitiveWrappers
	}
	return false
}

func (m *ScalaPbOptions) GetPrimitiveWrappers() bool {
	if m != nil && m.PrimitiveWrappers != nil {
		return *m.PrimitiveWrappers
	}
	return false
}

func (m *ScalaPbOptions) GetCollectionType() string {
	if m != nil && m.CollectionType != nil {
		return *m.CollectionType
	}
	return ""
}

func (m *ScalaPbOptions) GetPreserveUnknownFields() bool {
	if m != nil && m.PreserveUnknownFields != nil {
		return *m.PreserveUnknownFields
	}
	return Default_ScalaPbOptions_PreserveUnknownFields
}

func (m *ScalaPbOptions) GetObjectName() string {
	if m != nil && m.ObjectName != nil {
		return *m.ObjectName
	}
	return ""
}

func (m *ScalaPbOptions) GetScope() ScalaPbOptions_OptionsScope {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return ScalaPbOptions_FILE
}

func (m *ScalaPbOptions) GetLenses() bool {
	if m != nil && m.Lenses != nil {
		return *m.Lenses
	}
	return Default_ScalaPbOptions_Lenses
}

func (m *ScalaPbOptions) GetRetainSourceCodeInfo() bool {
	if m != nil && m.RetainSourceCodeInfo != nil {
		return *m.RetainSourceCodeInfo
	}
	return false
}

func (m *ScalaPbOptions) GetMapType() string {
	if m != nil && m.MapType != nil {
		return *m.MapType
	}
	return ""
}

func (m *ScalaPbOptions) GetNoDefaultValuesInConstructor() bool {
	if m != nil && m.NoDefaultValuesInConstructor != nil {
		return *m.NoDefaultValuesInConstructor
	}
	return false
}

func (m *ScalaPbOptions) GetEnumValueNaming() ScalaPbOptions_EnumValueNaming {
	if m != nil && m.EnumValueNaming != nil {
		return *m.EnumValueNaming
	}
	return ScalaPbOptions_AS_IN_PROTO
}

func (m *ScalaPbOptions) GetEnumStripPrefix() bool {
	if m != nil && m.EnumStripPrefix != nil {
		return *m.EnumStripPrefix
	}
	return Default_ScalaPbOptions_EnumStripPrefix
}

func (m *ScalaPbOptions) GetBytesType() string {
	if m != nil && m.BytesType != nil {
		return *m.BytesType
	}
	return ""
}

func (m *ScalaPbOptions) GetJavaConversions() bool {
	if m != nil && m.JavaConversions != nil {
		return *m.JavaConversions
	}
	return false
}

func (m *ScalaPbOptions) GetAuxMessageOptions() []*ScalaPbOptions_AuxMessageOptions {
	if m != nil {
		return m.AuxMessageOptions
	}
	return nil
}

func (m *ScalaPbOptions) GetAuxFieldOptions() []*ScalaPbOptions_AuxFieldOptions {
	if m != nil {
		return m.AuxFieldOptions
	}
	return nil
}

func (m *ScalaPbOptions) GetAuxEnumOptions() []*ScalaPbOptions_AuxEnumOptions {
	if m != nil {
		return m.AuxEnumOptions
	}
	return nil
}

func (m *ScalaPbOptions) GetAuxEnumValueOptions() []*ScalaPbOptions_AuxEnumValueOptions {
	if m != nil {
		return m.AuxEnumValueOptions
	}
	return nil
}

func (m *ScalaPbOptions) GetTestOnlyNoJavaConversions() bool {
	if m != nil && m.TestOnlyNoJavaConversions != nil {
		return *m.TestOnlyNoJavaConversions
	}
	return false
}

// AuxMessageOptions enables you to set message-level options through package-scoped options.
// This is useful when you can't add a dependency on scalapb.proto from the proto file that
// defines the message.
type ScalaPbOptions_AuxMessageOptions struct {
	// The fully-qualified name of the message in the proto name space.
	Target *string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	// Options to apply to the message. If there are any options defined on the target message
	// they take precedence over the options.
	Options              *MessageOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ScalaPbOptions_AuxMessageOptions) Reset()         { *m = ScalaPbOptions_AuxMessageOptions{} }
func (m *ScalaPbOptions_AuxMessageOptions) String() string { return proto.CompactTextString(m) }
func (*ScalaPbOptions_AuxMessageOptions) ProtoMessage()    {}
func (*ScalaPbOptions_AuxMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{0, 0}
}

func (m *ScalaPbOptions_AuxMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalaPbOptions_AuxMessageOptions.Unmarshal(m, b)
}
func (m *ScalaPbOptions_AuxMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalaPbOptions_AuxMessageOptions.Marshal(b, m, deterministic)
}
func (m *ScalaPbOptions_AuxMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalaPbOptions_AuxMessageOptions.Merge(m, src)
}
func (m *ScalaPbOptions_AuxMessageOptions) XXX_Size() int {
	return xxx_messageInfo_ScalaPbOptions_AuxMessageOptions.Size(m)
}
func (m *ScalaPbOptions_AuxMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalaPbOptions_AuxMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ScalaPbOptions_AuxMessageOptions proto.InternalMessageInfo

func (m *ScalaPbOptions_AuxMessageOptions) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *ScalaPbOptions_AuxMessageOptions) GetOptions() *MessageOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// AuxFieldOptions enables you to set field-level options through package-scoped options.
// This is useful when you can't add a dependency on scalapb.proto from the proto file that
// defines the field.
type ScalaPbOptions_AuxFieldOptions struct {
	// The fully-qualified name of the field in the proto name space.
	Target *string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	// Options to apply to the field. If there are any options defined on the target message
	// they take precedence over the options.
	Options              *FieldOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ScalaPbOptions_AuxFieldOptions) Reset()         { *m = ScalaPbOptions_AuxFieldOptions{} }
func (m *ScalaPbOptions_AuxFieldOptions) String() string { return proto.CompactTextString(m) }
func (*ScalaPbOptions_AuxFieldOptions) ProtoMessage()    {}
func (*ScalaPbOptions_AuxFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{0, 1}
}

func (m *ScalaPbOptions_AuxFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalaPbOptions_AuxFieldOptions.Unmarshal(m, b)
}
func (m *ScalaPbOptions_AuxFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalaPbOptions_AuxFieldOptions.Marshal(b, m, deterministic)
}
func (m *ScalaPbOptions_AuxFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalaPbOptions_AuxFieldOptions.Merge(m, src)
}
func (m *ScalaPbOptions_AuxFieldOptions) XXX_Size() int {
	return xxx_messageInfo_ScalaPbOptions_AuxFieldOptions.Size(m)
}
func (m *ScalaPbOptions_AuxFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalaPbOptions_AuxFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ScalaPbOptions_AuxFieldOptions proto.InternalMessageInfo

func (m *ScalaPbOptions_AuxFieldOptions) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *ScalaPbOptions_AuxFieldOptions) GetOptions() *FieldOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// AuxEnumOptions enables you to set enum-level options through package-scoped options.
// This is useful when you can't add a dependency on scalapb.proto from the proto file that
// defines the enum.
type ScalaPbOptions_AuxEnumOptions struct {
	// The fully-qualified name of the enum in the proto name space.
	Target *string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	// Options to apply to the enum. If there are any options defined on the target enum
	// they take precedence over the options.
	Options              *EnumOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ScalaPbOptions_AuxEnumOptions) Reset()         { *m = ScalaPbOptions_AuxEnumOptions{} }
func (m *ScalaPbOptions_AuxEnumOptions) String() string { return proto.CompactTextString(m) }
func (*ScalaPbOptions_AuxEnumOptions) ProtoMessage()    {}
func (*ScalaPbOptions_AuxEnumOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{0, 2}
}

func (m *ScalaPbOptions_AuxEnumOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalaPbOptions_AuxEnumOptions.Unmarshal(m, b)
}
func (m *ScalaPbOptions_AuxEnumOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalaPbOptions_AuxEnumOptions.Marshal(b, m, deterministic)
}
func (m *ScalaPbOptions_AuxEnumOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalaPbOptions_AuxEnumOptions.Merge(m, src)
}
func (m *ScalaPbOptions_AuxEnumOptions) XXX_Size() int {
	return xxx_messageInfo_ScalaPbOptions_AuxEnumOptions.Size(m)
}
func (m *ScalaPbOptions_AuxEnumOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalaPbOptions_AuxEnumOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ScalaPbOptions_AuxEnumOptions proto.InternalMessageInfo

func (m *ScalaPbOptions_AuxEnumOptions) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *ScalaPbOptions_AuxEnumOptions) GetOptions() *EnumOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// AuxEnumValueOptions enables you to set enum value level options through package-scoped
// options.  This is useful when you can't add a dependency on scalapb.proto from the proto
// file that defines the enum.
type ScalaPbOptions_AuxEnumValueOptions struct {
	// The fully-qualified name of the enum value in the proto name space.
	Target *string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	// Options to apply to the enum value. If there are any options defined on
	// the target enum value they take precedence over the options.
	Options              *EnumValueOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScalaPbOptions_AuxEnumValueOptions) Reset()         { *m = ScalaPbOptions_AuxEnumValueOptions{} }
func (m *ScalaPbOptions_AuxEnumValueOptions) String() string { return proto.CompactTextString(m) }
func (*ScalaPbOptions_AuxEnumValueOptions) ProtoMessage()    {}
func (*ScalaPbOptions_AuxEnumValueOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{0, 3}
}

func (m *ScalaPbOptions_AuxEnumValueOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalaPbOptions_AuxEnumValueOptions.Unmarshal(m, b)
}
func (m *ScalaPbOptions_AuxEnumValueOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalaPbOptions_AuxEnumValueOptions.Marshal(b, m, deterministic)
}
func (m *ScalaPbOptions_AuxEnumValueOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalaPbOptions_AuxEnumValueOptions.Merge(m, src)
}
func (m *ScalaPbOptions_AuxEnumValueOptions) XXX_Size() int {
	return xxx_messageInfo_ScalaPbOptions_AuxEnumValueOptions.Size(m)
}
func (m *ScalaPbOptions_AuxEnumValueOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalaPbOptions_AuxEnumValueOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ScalaPbOptions_AuxEnumValueOptions proto.InternalMessageInfo

func (m *ScalaPbOptions_AuxEnumValueOptions) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

func (m *ScalaPbOptions_AuxEnumValueOptions) GetOptions() *EnumValueOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type MessageOptions struct {
	// Additional classes and traits to mix in to the case class.
	Extends []string `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	// Additional classes and traits to mix in to the companion object.
	CompanionExtends []string `protobuf:"bytes,2,rep,name=companion_extends,json=companionExtends" json:"companion_extends,omitempty"`
	// Custom annotations to add to the generated case class.
	Annotations []string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty"`
	// All instances of this message will be converted to this type. An implicit TypeMapper
	// must be present.
	Type *string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	// Custom annotations to add to the companion object of the generated class.
	CompanionAnnotations []string `protobuf:"bytes,5,rep,name=companion_annotations,json=companionAnnotations" json:"companion_annotations,omitempty"`
	// Additional classes and traits to mix in to generated sealed_oneof base trait.
	SealedOneofExtends []string `protobuf:"bytes,6,rep,name=sealed_oneof_extends,json=sealedOneofExtends" json:"sealed_oneof_extends,omitempty"`
	// If true, when this message is used as an optional field, do not wrap it in an `Option`.
	// This is equivalent of setting `(field).no_box` to true on each field with the message type.
	NoBox *bool `protobuf:"varint,7,opt,name=no_box,json=noBox" json:"no_box,omitempty"`
	// Custom annotations to add to the generated `unknownFields` case class field.
	UnknownFieldsAnnotations     []string `protobuf:"bytes,8,rep,name=unknown_fields_annotations,json=unknownFieldsAnnotations" json:"unknown_fields_annotations,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *MessageOptions) Reset()         { *m = MessageOptions{} }
func (m *MessageOptions) String() string { return proto.CompactTextString(m) }
func (*MessageOptions) ProtoMessage()    {}
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{1}
}

var extRange_MessageOptions = []proto.ExtensionRange{
	{Start: 10000, End: 536870911},
}

func (*MessageOptions) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_MessageOptions
}

func (m *MessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOptions.Unmarshal(m, b)
}
func (m *MessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOptions.Marshal(b, m, deterministic)
}
func (m *MessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOptions.Merge(m, src)
}
func (m *MessageOptions) XXX_Size() int {
	return xxx_messageInfo_MessageOptions.Size(m)
}
func (m *MessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOptions proto.InternalMessageInfo

func (m *MessageOptions) GetExtends() []string {
	if m != nil {
		return m.Extends
	}
	return nil
}

func (m *MessageOptions) GetCompanionExtends() []string {
	if m != nil {
		return m.CompanionExtends
	}
	return nil
}

func (m *MessageOptions) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *MessageOptions) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *MessageOptions) GetCompanionAnnotations() []string {
	if m != nil {
		return m.CompanionAnnotations
	}
	return nil
}

func (m *MessageOptions) GetSealedOneofExtends() []string {
	if m != nil {
		return m.SealedOneofExtends
	}
	return nil
}

func (m *MessageOptions) GetNoBox() bool {
	if m != nil && m.NoBox != nil {
		return *m.NoBox
	}
	return false
}

func (m *MessageOptions) GetUnknownFieldsAnnotations() []string {
	if m != nil {
		return m.UnknownFieldsAnnotations
	}
	return nil
}

type FieldOptions struct {
	Type      *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	ScalaName *string `protobuf:"bytes,2,opt,name=scala_name,json=scalaName" json:"scala_name,omitempty"`
	// Can be specified only if this field is repeated. If unspecified,
	// it falls back to the file option named `collection_type`, which defaults
	// to `scala.collection.Seq`.
	CollectionType *string `protobuf:"bytes,3,opt,name=collection_type,json=collectionType" json:"collection_type,omitempty"`
	// If the field is a map, you can specify custom Scala types for the key
	// or value.
	KeyType   *string `protobuf:"bytes,4,opt,name=key_type,json=keyType" json:"key_type,omitempty"`
	ValueType *string `protobuf:"bytes,5,opt,name=value_type,json=valueType" json:"value_type,omitempty"`
	// Custom annotations to add to the field.
	Annotations []string `protobuf:"bytes,6,rep,name=annotations" json:"annotations,omitempty"`
	// Can be specified only if this field is a map. If unspecified,
	// it falls back to the file option named `map_type` which defaults to
	// `scala.collection.immutable.Map`
	MapType *string `protobuf:"bytes,7,opt,name=map_type,json=mapType" json:"map_type,omitempty"`
	// Do not box this value in Option[T]. If set, this overrides MessageOptions.no_box
	NoBox                        *bool    `protobuf:"varint,30,opt,name=no_box,json=noBox" json:"no_box,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{2}
}

var extRange_FieldOptions = []proto.ExtensionRange{
	{Start: 10000, End: 536870911},
}

func (*FieldOptions) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_FieldOptions
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *FieldOptions) GetScalaName() string {
	if m != nil && m.ScalaName != nil {
		return *m.ScalaName
	}
	return ""
}

func (m *FieldOptions) GetCollectionType() string {
	if m != nil && m.CollectionType != nil {
		return *m.CollectionType
	}
	return ""
}

func (m *FieldOptions) GetKeyType() string {
	if m != nil && m.KeyType != nil {
		return *m.KeyType
	}
	return ""
}

func (m *FieldOptions) GetValueType() string {
	if m != nil && m.ValueType != nil {
		return *m.ValueType
	}
	return ""
}

func (m *FieldOptions) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *FieldOptions) GetMapType() string {
	if m != nil && m.MapType != nil {
		return *m.MapType
	}
	return ""
}

func (m *FieldOptions) GetNoBox() bool {
	if m != nil && m.NoBox != nil {
		return *m.NoBox
	}
	return false
}

type EnumOptions struct {
	// Additional classes and traits to mix in to the base trait
	Extends []string `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	// Additional classes and traits to mix in to the companion object.
	CompanionExtends []string `protobuf:"bytes,2,rep,name=companion_extends,json=companionExtends" json:"companion_extends,omitempty"`
	// All instances of this enum will be converted to this type. An implicit TypeMapper
	// must be present.
	Type                         *string  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *EnumOptions) Reset()         { *m = EnumOptions{} }
func (m *EnumOptions) String() string { return proto.CompactTextString(m) }
func (*EnumOptions) ProtoMessage()    {}
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{3}
}

var extRange_EnumOptions = []proto.ExtensionRange{
	{Start: 10000, End: 536870911},
}

func (*EnumOptions) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_EnumOptions
}

func (m *EnumOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumOptions.Unmarshal(m, b)
}
func (m *EnumOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumOptions.Marshal(b, m, deterministic)
}
func (m *EnumOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumOptions.Merge(m, src)
}
func (m *EnumOptions) XXX_Size() int {
	return xxx_messageInfo_EnumOptions.Size(m)
}
func (m *EnumOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EnumOptions proto.InternalMessageInfo

func (m *EnumOptions) GetExtends() []string {
	if m != nil {
		return m.Extends
	}
	return nil
}

func (m *EnumOptions) GetCompanionExtends() []string {
	if m != nil {
		return m.CompanionExtends
	}
	return nil
}

func (m *EnumOptions) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type EnumValueOptions struct {
	// Additional classes and traits to mix in to an individual enum value.
	Extends []string `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	// Name in Scala to use for this enum value.
	ScalaName                    *string  `protobuf:"bytes,2,opt,name=scala_name,json=scalaName" json:"scala_name,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *EnumValueOptions) Reset()         { *m = EnumValueOptions{} }
func (m *EnumValueOptions) String() string { return proto.CompactTextString(m) }
func (*EnumValueOptions) ProtoMessage()    {}
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{4}
}

var extRange_EnumValueOptions = []proto.ExtensionRange{
	{Start: 10000, End: 536870911},
}

func (*EnumValueOptions) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_EnumValueOptions
}

func (m *EnumValueOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumValueOptions.Unmarshal(m, b)
}
func (m *EnumValueOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumValueOptions.Marshal(b, m, deterministic)
}
func (m *EnumValueOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumValueOptions.Merge(m, src)
}
func (m *EnumValueOptions) XXX_Size() int {
	return xxx_messageInfo_EnumValueOptions.Size(m)
}
func (m *EnumValueOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumValueOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EnumValueOptions proto.InternalMessageInfo

func (m *EnumValueOptions) GetExtends() []string {
	if m != nil {
		return m.Extends
	}
	return nil
}

func (m *EnumValueOptions) GetScalaName() string {
	if m != nil && m.ScalaName != nil {
		return *m.ScalaName
	}
	return ""
}

type OneofOptions struct {
	// Additional traits to mix in to a oneof.
	Extends []string `protobuf:"bytes,1,rep,name=extends" json:"extends,omitempty"`
	// Name in Scala to use for this oneof field.
	ScalaName                    *string  `protobuf:"bytes,2,opt,name=scala_name,json=scalaName" json:"scala_name,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *OneofOptions) Reset()         { *m = OneofOptions{} }
func (m *OneofOptions) String() string { return proto.CompactTextString(m) }
func (*OneofOptions) ProtoMessage()    {}
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_bebbee629788eee9, []int{5}
}

var extRange_OneofOptions = []proto.ExtensionRange{
	{Start: 10000, End: 536870911},
}

func (*OneofOptions) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_OneofOptions
}

func (m *OneofOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofOptions.Unmarshal(m, b)
}
func (m *OneofOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofOptions.Marshal(b, m, deterministic)
}
func (m *OneofOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofOptions.Merge(m, src)
}
func (m *OneofOptions) XXX_Size() int {
	return xxx_messageInfo_OneofOptions.Size(m)
}
func (m *OneofOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofOptions.DiscardUnknown(m)
}

var xxx_messageInfo_OneofOptions proto.InternalMessageInfo

func (m *OneofOptions) GetExtends() []string {
	if m != nil {
		return m.Extends
	}
	return nil
}

func (m *OneofOptions) GetScalaName() string {
	if m != nil && m.ScalaName != nil {
		return *m.ScalaName
	}
	return ""
}

var E_Options = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FileOptions)(nil),
	ExtensionType: (*ScalaPbOptions)(nil),
	Field:         1020,
	Name:          "scalapb.options",
	Tag:           "bytes,1020,opt,name=options",
	Filename:      "proto/scalapb/scalapb.proto",
}

var E_Message = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*MessageOptions)(nil),
	Field:         1020,
	Name:          "scalapb.message",
	Tag:           "bytes,1020,opt,name=message",
	Filename:      "proto/scalapb/scalapb.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         1020,
	Name:          "scalapb.field",
	Tag:           "bytes,1020,opt,name=field",
	Filename:      "proto/scalapb/scalapb.proto",
}

var E_EnumOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.EnumOptions)(nil),
	ExtensionType: (*EnumOptions)(nil),
	Field:         1020,
	Name:          "scalapb.enum_options",
	Tag:           "bytes,1020,opt,name=enum_options",
	Filename:      "proto/scalapb/scalapb.proto",
}

var E_EnumValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
	ExtensionType: (*EnumValueOptions)(nil),
	Field:         1020,
	Name:          "scalapb.enum_value",
	Tag:           "bytes,1020,opt,name=enum_value",
	Filename:      "proto/scalapb/scalapb.proto",
}

var E_Oneof = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.OneofOptions)(nil),
	ExtensionType: (*OneofOptions)(nil),
	Field:         1020,
	Name:          "scalapb.oneof",
	Tag:           "bytes,1020,opt,name=oneof",
	Filename:      "proto/scalapb/scalapb.proto",
}

func init() {
	proto.RegisterEnum("scalapb.ScalaPbOptions_OptionsScope", ScalaPbOptions_OptionsScope_name, ScalaPbOptions_OptionsScope_value)
	proto.RegisterEnum("scalapb.ScalaPbOptions_EnumValueNaming", ScalaPbOptions_EnumValueNaming_name, ScalaPbOptions_EnumValueNaming_value)
	proto.RegisterType((*ScalaPbOptions)(nil), "scalapb.ScalaPbOptions")
	proto.RegisterType((*ScalaPbOptions_AuxMessageOptions)(nil), "scalapb.ScalaPbOptions.AuxMessageOptions")
	proto.RegisterType((*ScalaPbOptions_AuxFieldOptions)(nil), "scalapb.ScalaPbOptions.AuxFieldOptions")
	proto.RegisterType((*ScalaPbOptions_AuxEnumOptions)(nil), "scalapb.ScalaPbOptions.AuxEnumOptions")
	proto.RegisterType((*ScalaPbOptions_AuxEnumValueOptions)(nil), "scalapb.ScalaPbOptions.AuxEnumValueOptions")
	proto.RegisterType((*MessageOptions)(nil), "scalapb.MessageOptions")
	proto.RegisterType((*FieldOptions)(nil), "scalapb.FieldOptions")
	proto.RegisterType((*EnumOptions)(nil), "scalapb.EnumOptions")
	proto.RegisterType((*EnumValueOptions)(nil), "scalapb.EnumValueOptions")
	proto.RegisterType((*OneofOptions)(nil), "scalapb.OneofOptions")
	proto.RegisterExtension(E_Options)
	proto.RegisterExtension(E_Message)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_EnumOptions)
	proto.RegisterExtension(E_EnumValue)
	proto.RegisterExtension(E_Oneof)
}

func init() { proto.RegisterFile("proto/scalapb/scalapb.proto", fileDescriptor_bebbee629788eee9) }

var fileDescriptor_bebbee629788eee9 = []byte{
	// 1239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdd, 0x4e, 0x1b, 0x47,
	0x14, 0xc7, 0x63, 0xc0, 0xd8, 0x1c, 0x13, 0xdb, 0x0c, 0x38, 0x2c, 0x34, 0x34, 0x0e, 0x6a, 0x0b,
	0x69, 0x54, 0xd3, 0x10, 0xf5, 0xc6, 0x8a, 0x54, 0x39, 0xae, 0xa9, 0x68, 0x12, 0xb0, 0xec, 0x94,
	0x7e, 0xa8, 0xea, 0x74, 0xbc, 0x1e, 0x5b, 0x1b, 0xd6, 0x33, 0xab, 0xfd, 0x20, 0xf6, 0x1d, 0x52,
	0x5f, 0xa0, 0x0f, 0xd7, 0x27, 0x68, 0xaf, 0xfa, 0x0e, 0xbd, 0xa8, 0xe6, 0xcc, 0xee, 0x7a, 0xd7,
	0x1f, 0xf4, 0x26, 0x57, 0x30, 0xe7, 0x9c, 0xf9, 0xcd, 0x9c, 0xff, 0x99, 0x3d, 0xc7, 0xf0, 0x91,
	0xe3, 0x4a, 0x5f, 0x9e, 0x78, 0x26, 0xb3, 0x99, 0xd3, 0x8b, 0xfe, 0xd6, 0xd0, 0x4a, 0x72, 0xe1,
	0x72, 0xbf, 0x3a, 0x94, 0x72, 0x68, 0xf3, 0x13, 0x34, 0xf7, 0x82, 0xc1, 0x49, 0x9f, 0x7b, 0xa6,
	0x6b, 0x39, 0xbe, 0x74, 0x75, 0xe8, 0xe1, 0xdf, 0xf7, 0xa1, 0xd8, 0x55, 0xd1, 0xed, 0xde, 0xa5,
	0xe3, 0x5b, 0x52, 0x78, 0xe4, 0x31, 0x6c, 0x3a, 0xcc, 0xbc, 0x66, 0x43, 0x4e, 0x05, 0x1b, 0x71,
	0x23, 0x53, 0xcd, 0x1c, 0x6f, 0x74, 0x0a, 0xa1, 0xed, 0x82, 0x8d, 0xb8, 0x0a, 0x19, 0xd8, 0xcc,
	0xa7, 0xa1, 0xcd, 0x58, 0xa9, 0x66, 0x8e, 0xf3, 0x9d, 0x82, 0xb2, 0xb5, 0xb5, 0x89, 0x3c, 0x80,
	0x75, 0x6b, 0xe4, 0x48, 0xd7, 0x37, 0x56, 0xab, 0xab, 0xc7, 0x1b, 0x9d, 0x70, 0x45, 0xf6, 0x21,
	0xef, 0xb8, 0x9c, 0x8d, 0x7a, 0x36, 0x37, 0xd6, 0xd0, 0x13, 0xaf, 0xc9, 0x23, 0x28, 0x78, 0x96,
	0x18, 0xda, 0x9c, 0x0e, 0x2c, 0x9b, 0x1b, 0x59, 0xa4, 0x82, 0x36, 0x9d, 0x59, 0x36, 0x27, 0xa7,
	0x50, 0x11, 0x92, 0x3a, 0xae, 0x35, 0xb2, 0x7c, 0xeb, 0x86, 0xd3, 0xf7, 0x2e, 0x73, 0x1c, 0xee,
	0x7a, 0x46, 0x0e, 0x43, 0xb7, 0x85, 0x6c, 0x47, 0xbe, 0x1f, 0x42, 0x17, 0xf9, 0x02, 0xc8, 0x82,
	0x0d, 0xeb, 0xb8, 0x61, 0xcb, 0x99, 0x0b, 0x3f, 0x82, 0x92, 0x29, 0x6d, 0x9b, 0x9b, 0x4a, 0x0c,
	0xea, 0x4f, 0x1c, 0x6e, 0xe4, 0x51, 0x80, 0xe2, 0xd4, 0xfc, 0x76, 0xe2, 0x70, 0xf2, 0x02, 0x76,
	0x1d, 0x97, 0x7b, 0xdc, 0xbd, 0xe1, 0x34, 0x10, 0xd7, 0x42, 0xbe, 0x17, 0x74, 0x60, 0x71, 0xbb,
	0xef, 0x19, 0x1b, 0x0a, 0x5e, 0x5f, 0xf3, 0xdd, 0x80, 0x77, 0x2a, 0x51, 0xd0, 0xf7, 0x3a, 0xe6,
	0x0c, 0x43, 0x54, 0xaa, 0xb2, 0xf7, 0x8e, 0x9b, 0xbe, 0xd6, 0x18, 0xf0, 0x08, 0xd0, 0x26, 0x94,
	0xb8, 0x0e, 0x59, 0xcf, 0x94, 0x0e, 0x37, 0x0a, 0xd5, 0xcc, 0x71, 0xf1, 0xf4, 0x93, 0x5a, 0x54,
	0xe2, 0x74, 0xb5, 0x6a, 0xe1, 0xdf, 0xae, 0x8a, 0xed, 0xe8, 0x2d, 0xe4, 0x21, 0xac, 0xdb, 0x5c,
	0x78, 0xdc, 0x33, 0x36, 0x13, 0x37, 0x09, 0x6d, 0xe4, 0x2b, 0xd8, 0x75, 0xb9, 0xcf, 0x2c, 0x41,
	0x3d, 0x19, 0xb8, 0x26, 0xa7, 0xa6, 0xec, 0x73, 0x6a, 0x89, 0x81, 0x34, 0xee, 0xa3, 0x2a, 0x3b,
	0xda, 0xdd, 0x45, 0x6f, 0x53, 0xf6, 0xf9, 0xb9, 0x18, 0x48, 0xb2, 0x07, 0xf9, 0x11, 0x73, 0xb4,
	0x22, 0x45, 0xbc, 0x6e, 0x6e, 0xc4, 0x1c, 0x94, 0xe2, 0x0c, 0xaa, 0x42, 0xd2, 0x3e, 0x1f, 0xb0,
	0xc0, 0xf6, 0xe9, 0x0d, 0xb3, 0x03, 0xee, 0x51, 0x4b, 0x50, 0x53, 0x0a, 0xcf, 0x77, 0x03, 0xd3,
	0x97, 0xae, 0x51, 0x42, 0xf4, 0x43, 0x21, 0xbf, 0xd1, 0x61, 0x57, 0x18, 0x75, 0x2e, 0x9a, 0xd3,
	0x18, 0xd2, 0x85, 0x2d, 0x2e, 0x82, 0x91, 0x26, 0x28, 0x61, 0x2c, 0x31, 0x34, 0xca, 0x98, 0xff,
	0xd1, 0xb2, 0xfc, 0x5b, 0x22, 0x18, 0x21, 0xeb, 0x02, 0xc3, 0x3b, 0x25, 0x9e, 0x36, 0x90, 0x67,
	0x21, 0xd4, 0xf3, 0x5d, 0xcb, 0xa1, 0x8e, 0xcb, 0x07, 0xd6, 0xd8, 0xd8, 0x42, 0x5d, 0xb2, 0x03,
	0x66, 0x7b, 0x5c, 0x6f, 0xe9, 0x2a, 0x77, 0x1b, 0xbd, 0xe4, 0x00, 0xa0, 0x37, 0xf1, 0xb9, 0xa7,
	0x93, 0xad, 0x60, 0xb2, 0x1b, 0x68, 0xc1, 0x74, 0x9f, 0x40, 0xf9, 0x1d, 0xbb, 0x61, 0x2a, 0xbd,
	0x1b, 0xee, 0x7a, 0xea, 0x1a, 0xc6, 0x2e, 0xa6, 0x57, 0x52, 0xf6, 0xe6, 0xd4, 0x4c, 0x7e, 0x82,
	0x6d, 0x16, 0x8c, 0xe9, 0x88, 0x7b, 0x9e, 0xfa, 0x9e, 0xa4, 0xbe, 0xb4, 0x41, 0xaa, 0xab, 0xc7,
	0x85, 0xd3, 0x27, 0xcb, 0x72, 0x6a, 0x04, 0xe3, 0x37, 0x7a, 0x47, 0x68, 0xe9, 0x6c, 0xb1, 0x59,
	0x93, 0x12, 0x4b, 0xa1, 0xf1, 0xc9, 0xc5, 0xe0, 0x6d, 0x04, 0x1f, 0xdd, 0x01, 0xc6, 0xf7, 0x17,
	0x61, 0x4b, 0x2c, 0x6d, 0x20, 0x6d, 0x28, 0x2b, 0x28, 0x0a, 0x16, 0x31, 0x77, 0x90, 0xf9, 0xd9,
	0x1d, 0x4c, 0x55, 0x83, 0x08, 0x59, 0x64, 0xa9, 0x35, 0xf9, 0x0d, 0x1e, 0xc4, 0x44, 0x5d, 0xd7,
	0x88, 0xfb, 0x00, 0xb9, 0x4f, 0xff, 0x87, 0x8b, 0xa5, 0x8c, 0xe0, 0xdb, 0x6c, 0xde, 0x48, 0x1a,
	0x70, 0xe0, 0x73, 0xcf, 0xa7, 0x52, 0xd8, 0x13, 0x2a, 0x24, 0x9d, 0xab, 0xcd, 0x3f, 0xba, 0x3b,
	0xec, 0xa9, 0xa8, 0x4b, 0x61, 0x4f, 0x2e, 0xe4, 0x77, 0xe9, 0x32, 0xed, 0xff, 0x0a, 0x5b, 0x73,
	0x9a, 0xab, 0x0e, 0xe6, 0x33, 0x77, 0xc8, 0xfd, 0xb0, 0x03, 0x86, 0x2b, 0xf2, 0x0c, 0x72, 0x51,
	0x0a, 0xaa, 0xef, 0x15, 0x4e, 0x77, 0xe3, 0x14, 0x66, 0xaa, 0x16, 0xc5, 0xed, 0xff, 0x0c, 0xa5,
	0x19, 0xe9, 0x97, 0xd2, 0x4f, 0x66, 0xe9, 0x95, 0x98, 0x9e, 0x2a, 0x5d, 0xcc, 0xfe, 0x11, 0x8a,
	0xe9, 0x12, 0x2c, 0x45, 0xd7, 0x66, 0xd1, 0x3b, 0x31, 0x3a, 0x59, 0xc1, 0x98, 0xdc, 0x83, 0xed,
	0x05, 0x45, 0x58, 0x8a, 0x7f, 0x3e, 0x8b, 0xdf, 0x4b, 0xe1, 0x53, 0x85, 0x8c, 0x22, 0x0f, 0x3f,
	0x85, 0xcd, 0x64, 0x07, 0x23, 0x79, 0x58, 0x3b, 0x3b, 0x7f, 0xdd, 0x2a, 0xdf, 0x23, 0x05, 0xc8,
	0xb5, 0x1b, 0xcd, 0x57, 0x8d, 0x6f, 0x5b, 0xe5, 0xcc, 0xe1, 0x29, 0x94, 0x66, 0x3e, 0x74, 0x52,
	0x82, 0x42, 0xa3, 0x4b, 0xcf, 0x2f, 0x68, 0xbb, 0x73, 0xf9, 0xf6, 0xb2, 0x7c, 0x8f, 0x14, 0x01,
	0x9a, 0x8d, 0x37, 0xad, 0xd7, 0xb4, 0xd9, 0xe8, 0xb6, 0xca, 0x99, 0xcf, 0x37, 0xf2, 0x7f, 0x5c,
	0x94, 0x6f, 0x6f, 0x6f, 0x6f, 0x57, 0x0e, 0xff, 0x5c, 0x81, 0xe2, 0x4c, 0x75, 0x0d, 0xc8, 0xf1,
	0xb1, 0xcf, 0x45, 0xdf, 0x33, 0x32, 0x38, 0x86, 0xa2, 0x25, 0x79, 0x0a, 0x5b, 0xa6, 0x1c, 0x39,
	0x4c, 0xa8, 0x01, 0x10, 0xc5, 0xac, 0x60, 0x4c, 0x39, 0x76, 0xb4, 0xc2, 0xe0, 0x2a, 0x14, 0x98,
	0x10, 0xd2, 0x67, 0x3a, 0x71, 0x3d, 0xeb, 0x92, 0x26, 0x42, 0x60, 0x0d, 0xdb, 0xc8, 0x1a, 0x8a,
	0x85, 0xff, 0x93, 0xe7, 0x50, 0x99, 0x1e, 0x91, 0xdc, 0x9f, 0xc5, 0xfd, 0x3b, 0xb1, 0xb3, 0x91,
	0x00, 0x7d, 0x09, 0x3b, 0x1e, 0x67, 0x36, 0xef, 0x53, 0x29, 0xb8, 0x1c, 0xc4, 0x57, 0x5b, 0xc7,
	0x3d, 0x44, 0xfb, 0x2e, 0x95, 0x2b, 0xba, 0x5c, 0x05, 0xd6, 0x85, 0xa4, 0x3d, 0x39, 0x0e, 0xe7,
	0x63, 0x56, 0xc8, 0x97, 0x72, 0x4c, 0x5e, 0xc0, 0x7e, 0x7a, 0x60, 0xa5, 0xae, 0x90, 0x47, 0x9c,
	0x11, 0x24, 0xc7, 0x55, 0xe2, 0x1a, 0x49, 0x59, 0x7f, 0x5f, 0x81, 0xcd, 0xd4, 0xa3, 0x8e, 0x72,
	0xcd, 0x24, 0x72, 0x3d, 0x00, 0xc0, 0x67, 0xa0, 0x07, 0xdd, 0x8a, 0x6e, 0xa6, 0x68, 0xc1, 0x39,
	0xb7, 0x60, 0xde, 0xae, 0x2e, 0x9c, 0xb7, 0x7b, 0x90, 0xbf, 0xe6, 0x13, 0x9a, 0xd0, 0x32, 0x77,
	0xcd, 0x27, 0x6f, 0xc3, 0x23, 0x74, 0x6b, 0x41, 0x67, 0x56, 0x1f, 0x81, 0x16, 0x74, 0xcf, 0xd4,
	0x68, 0x7d, 0xbe, 0x46, 0xc9, 0xd9, 0x96, 0x4b, 0xcf, 0xb6, 0xa9, 0x86, 0x1f, 0x27, 0x34, 0x4c,
	0xaa, 0xe0, 0x41, 0x21, 0xf9, 0xf5, 0x7d, 0xa0, 0x87, 0x15, 0x49, 0xb9, 0x3a, 0x95, 0x32, 0x79,
	0xe8, 0x15, 0x94, 0xe7, 0x3e, 0xcc, 0xe5, 0x27, 0xdf, 0x5d, 0x83, 0x24, 0xb7, 0x03, 0x9b, 0xf8,
	0x84, 0x3e, 0x20, 0xb3, 0xde, 0x8e, 0x1b, 0x03, 0x79, 0x58, 0xd3, 0xbf, 0x48, 0x6b, 0xd1, 0x2f,
	0xd2, 0x9a, 0xfa, 0x5d, 0x17, 0x1e, 0x66, 0xfc, 0x9b, 0x9b, 0xe9, 0xa7, 0xe9, 0x91, 0x10, 0x77,
	0x8d, 0x7a, 0x17, 0x72, 0xe1, 0x48, 0x25, 0x8f, 0xe6, 0x88, 0xe9, 0x0f, 0x7d, 0x1e, 0x3a, 0xdb,
	0xa4, 0x43, 0x52, 0xfd, 0x15, 0x64, 0xf1, 0x73, 0x20, 0x07, 0x0b, 0x2e, 0x39, 0x7d, 0xe4, 0x11,
	0x70, 0x49, 0x5f, 0xd6, 0x8c, 0xfa, 0x15, 0x6c, 0x26, 0x87, 0xe8, 0x82, 0xc4, 0x13, 0x6f, 0x26,
	0x42, 0x2e, 0xee, 0xc7, 0x05, 0x3e, 0x5d, 0xd4, 0x7f, 0x01, 0x98, 0x8e, 0x52, 0xf2, 0x78, 0x21,
	0x35, 0xf9, 0x28, 0x22, 0xf4, 0x1d, 0xbd, 0x78, 0x23, 0xfe, 0xc5, 0xa4, 0x24, 0xc0, 0xde, 0xb2,
	0x40, 0x82, 0xe4, 0xab, 0x98, 0x97, 0x20, 0xe9, 0xed, 0x68, 0xc6, 0xcb, 0x23, 0x28, 0x45, 0xee,
	0x50, 0x85, 0xbf, 0xbe, 0xde, 0x9e, 0xb3, 0x95, 0x33, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x03,
	0xe1, 0x89, 0x47, 0xcc, 0x0c, 0x00, 0x00,
}
