// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CasperMessage.proto

package casper_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	_ "rchain/api/pb/scalapb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HasBlockRequestProto struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasBlockRequestProto) Reset()         { *m = HasBlockRequestProto{} }
func (m *HasBlockRequestProto) String() string { return proto.CompactTextString(m) }
func (*HasBlockRequestProto) ProtoMessage()    {}
func (*HasBlockRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{0}
}

func (m *HasBlockRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasBlockRequestProto.Unmarshal(m, b)
}
func (m *HasBlockRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasBlockRequestProto.Marshal(b, m, deterministic)
}
func (m *HasBlockRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasBlockRequestProto.Merge(m, src)
}
func (m *HasBlockRequestProto) XXX_Size() int {
	return xxx_messageInfo_HasBlockRequestProto.Size(m)
}
func (m *HasBlockRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_HasBlockRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_HasBlockRequestProto proto.InternalMessageInfo

func (m *HasBlockRequestProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type HasBlockProto struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasBlockProto) Reset()         { *m = HasBlockProto{} }
func (m *HasBlockProto) String() string { return proto.CompactTextString(m) }
func (*HasBlockProto) ProtoMessage()    {}
func (*HasBlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{1}
}

func (m *HasBlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasBlockProto.Unmarshal(m, b)
}
func (m *HasBlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasBlockProto.Marshal(b, m, deterministic)
}
func (m *HasBlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasBlockProto.Merge(m, src)
}
func (m *HasBlockProto) XXX_Size() int {
	return xxx_messageInfo_HasBlockProto.Size(m)
}
func (m *HasBlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_HasBlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_HasBlockProto proto.InternalMessageInfo

func (m *HasBlockProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BlockRequestProto struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequestProto) Reset()         { *m = BlockRequestProto{} }
func (m *BlockRequestProto) String() string { return proto.CompactTextString(m) }
func (*BlockRequestProto) ProtoMessage()    {}
func (*BlockRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{2}
}

func (m *BlockRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequestProto.Unmarshal(m, b)
}
func (m *BlockRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequestProto.Marshal(b, m, deterministic)
}
func (m *BlockRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequestProto.Merge(m, src)
}
func (m *BlockRequestProto) XXX_Size() int {
	return xxx_messageInfo_BlockRequestProto.Size(m)
}
func (m *BlockRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequestProto proto.InternalMessageInfo

func (m *BlockRequestProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ForkChoiceTipRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForkChoiceTipRequestProto) Reset()         { *m = ForkChoiceTipRequestProto{} }
func (m *ForkChoiceTipRequestProto) String() string { return proto.CompactTextString(m) }
func (*ForkChoiceTipRequestProto) ProtoMessage()    {}
func (*ForkChoiceTipRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{3}
}

func (m *ForkChoiceTipRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForkChoiceTipRequestProto.Unmarshal(m, b)
}
func (m *ForkChoiceTipRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForkChoiceTipRequestProto.Marshal(b, m, deterministic)
}
func (m *ForkChoiceTipRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForkChoiceTipRequestProto.Merge(m, src)
}
func (m *ForkChoiceTipRequestProto) XXX_Size() int {
	return xxx_messageInfo_ForkChoiceTipRequestProto.Size(m)
}
func (m *ForkChoiceTipRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ForkChoiceTipRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ForkChoiceTipRequestProto proto.InternalMessageInfo

// ---------- Signing Protocol ---------
type ApprovedBlockCandidateProto struct {
	Block                *BlockMessageProto `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	RequiredSigs         int32              `protobuf:"varint,2,opt,name=requiredSigs,proto3" json:"requiredSigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ApprovedBlockCandidateProto) Reset()         { *m = ApprovedBlockCandidateProto{} }
func (m *ApprovedBlockCandidateProto) String() string { return proto.CompactTextString(m) }
func (*ApprovedBlockCandidateProto) ProtoMessage()    {}
func (*ApprovedBlockCandidateProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{4}
}

func (m *ApprovedBlockCandidateProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovedBlockCandidateProto.Unmarshal(m, b)
}
func (m *ApprovedBlockCandidateProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovedBlockCandidateProto.Marshal(b, m, deterministic)
}
func (m *ApprovedBlockCandidateProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovedBlockCandidateProto.Merge(m, src)
}
func (m *ApprovedBlockCandidateProto) XXX_Size() int {
	return xxx_messageInfo_ApprovedBlockCandidateProto.Size(m)
}
func (m *ApprovedBlockCandidateProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovedBlockCandidateProto.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovedBlockCandidateProto proto.InternalMessageInfo

func (m *ApprovedBlockCandidateProto) GetBlock() *BlockMessageProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ApprovedBlockCandidateProto) GetRequiredSigs() int32 {
	if m != nil {
		return m.RequiredSigs
	}
	return 0
}

type UnapprovedBlockProto struct {
	Candidate            *ApprovedBlockCandidateProto `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Timestamp            int64                        `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration             int64                        `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UnapprovedBlockProto) Reset()         { *m = UnapprovedBlockProto{} }
func (m *UnapprovedBlockProto) String() string { return proto.CompactTextString(m) }
func (*UnapprovedBlockProto) ProtoMessage()    {}
func (*UnapprovedBlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{5}
}

func (m *UnapprovedBlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnapprovedBlockProto.Unmarshal(m, b)
}
func (m *UnapprovedBlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnapprovedBlockProto.Marshal(b, m, deterministic)
}
func (m *UnapprovedBlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnapprovedBlockProto.Merge(m, src)
}
func (m *UnapprovedBlockProto) XXX_Size() int {
	return xxx_messageInfo_UnapprovedBlockProto.Size(m)
}
func (m *UnapprovedBlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UnapprovedBlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_UnapprovedBlockProto proto.InternalMessageInfo

func (m *UnapprovedBlockProto) GetCandidate() *ApprovedBlockCandidateProto {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *UnapprovedBlockProto) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UnapprovedBlockProto) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type Signature struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Algorithm            string   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Sig                  []byte   `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{6}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Signature) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *Signature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type BlockApprovalProto struct {
	Candidate            *ApprovedBlockCandidateProto `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Sig                  *Signature                   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *BlockApprovalProto) Reset()         { *m = BlockApprovalProto{} }
func (m *BlockApprovalProto) String() string { return proto.CompactTextString(m) }
func (*BlockApprovalProto) ProtoMessage()    {}
func (*BlockApprovalProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{7}
}

func (m *BlockApprovalProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockApprovalProto.Unmarshal(m, b)
}
func (m *BlockApprovalProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockApprovalProto.Marshal(b, m, deterministic)
}
func (m *BlockApprovalProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockApprovalProto.Merge(m, src)
}
func (m *BlockApprovalProto) XXX_Size() int {
	return xxx_messageInfo_BlockApprovalProto.Size(m)
}
func (m *BlockApprovalProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockApprovalProto.DiscardUnknown(m)
}

var xxx_messageInfo_BlockApprovalProto proto.InternalMessageInfo

func (m *BlockApprovalProto) GetCandidate() *ApprovedBlockCandidateProto {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *BlockApprovalProto) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type ApprovedBlockProto struct {
	Candidate            *ApprovedBlockCandidateProto `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Sigs                 []*Signature                 `protobuf:"bytes,2,rep,name=sigs,proto3" json:"sigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ApprovedBlockProto) Reset()         { *m = ApprovedBlockProto{} }
func (m *ApprovedBlockProto) String() string { return proto.CompactTextString(m) }
func (*ApprovedBlockProto) ProtoMessage()    {}
func (*ApprovedBlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{8}
}

func (m *ApprovedBlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovedBlockProto.Unmarshal(m, b)
}
func (m *ApprovedBlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovedBlockProto.Marshal(b, m, deterministic)
}
func (m *ApprovedBlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovedBlockProto.Merge(m, src)
}
func (m *ApprovedBlockProto) XXX_Size() int {
	return xxx_messageInfo_ApprovedBlockProto.Size(m)
}
func (m *ApprovedBlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovedBlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovedBlockProto proto.InternalMessageInfo

func (m *ApprovedBlockProto) GetCandidate() *ApprovedBlockCandidateProto {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *ApprovedBlockProto) GetSigs() []*Signature {
	if m != nil {
		return m.Sigs
	}
	return nil
}

type ApprovedBlockRequestProto struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	TrimState            bool     `protobuf:"varint,2,opt,name=trimState,proto3" json:"trimState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApprovedBlockRequestProto) Reset()         { *m = ApprovedBlockRequestProto{} }
func (m *ApprovedBlockRequestProto) String() string { return proto.CompactTextString(m) }
func (*ApprovedBlockRequestProto) ProtoMessage()    {}
func (*ApprovedBlockRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{9}
}

func (m *ApprovedBlockRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovedBlockRequestProto.Unmarshal(m, b)
}
func (m *ApprovedBlockRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovedBlockRequestProto.Marshal(b, m, deterministic)
}
func (m *ApprovedBlockRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovedBlockRequestProto.Merge(m, src)
}
func (m *ApprovedBlockRequestProto) XXX_Size() int {
	return xxx_messageInfo_ApprovedBlockRequestProto.Size(m)
}
func (m *ApprovedBlockRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovedBlockRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovedBlockRequestProto proto.InternalMessageInfo

func (m *ApprovedBlockRequestProto) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *ApprovedBlockRequestProto) GetTrimState() bool {
	if m != nil {
		return m.TrimState
	}
	return false
}

type NoApprovedBlockAvailableProto struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	NodeIdentifer        string   `protobuf:"bytes,2,opt,name=nodeIdentifer,proto3" json:"nodeIdentifer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoApprovedBlockAvailableProto) Reset()         { *m = NoApprovedBlockAvailableProto{} }
func (m *NoApprovedBlockAvailableProto) String() string { return proto.CompactTextString(m) }
func (*NoApprovedBlockAvailableProto) ProtoMessage()    {}
func (*NoApprovedBlockAvailableProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{10}
}

func (m *NoApprovedBlockAvailableProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoApprovedBlockAvailableProto.Unmarshal(m, b)
}
func (m *NoApprovedBlockAvailableProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoApprovedBlockAvailableProto.Marshal(b, m, deterministic)
}
func (m *NoApprovedBlockAvailableProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoApprovedBlockAvailableProto.Merge(m, src)
}
func (m *NoApprovedBlockAvailableProto) XXX_Size() int {
	return xxx_messageInfo_NoApprovedBlockAvailableProto.Size(m)
}
func (m *NoApprovedBlockAvailableProto) XXX_DiscardUnknown() {
	xxx_messageInfo_NoApprovedBlockAvailableProto.DiscardUnknown(m)
}

var xxx_messageInfo_NoApprovedBlockAvailableProto proto.InternalMessageInfo

func (m *NoApprovedBlockAvailableProto) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *NoApprovedBlockAvailableProto) GetNodeIdentifer() string {
	if m != nil {
		return m.NodeIdentifer
	}
	return ""
}

// --------- Core Protocol  --------
type BlockMessageProto struct {
	BlockHash            []byte                `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Header               *HeaderProto          `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *BodyProto            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Justifications       []*JustificationProto `protobuf:"bytes,4,rep,name=justifications,proto3" json:"justifications,omitempty"`
	Sender               []byte                `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	SeqNum               int32                 `protobuf:"varint,6,opt,name=seqNum,proto3" json:"seqNum,omitempty"`
	Sig                  []byte                `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	SigAlgorithm         string                `protobuf:"bytes,8,opt,name=sigAlgorithm,proto3" json:"sigAlgorithm,omitempty"`
	ShardId              string                `protobuf:"bytes,9,opt,name=shardId,proto3" json:"shardId,omitempty"`
	ExtraBytes           []byte                `protobuf:"bytes,10,opt,name=extraBytes,proto3" json:"extraBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockMessageProto) Reset()         { *m = BlockMessageProto{} }
func (m *BlockMessageProto) String() string { return proto.CompactTextString(m) }
func (*BlockMessageProto) ProtoMessage()    {}
func (*BlockMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{11}
}

func (m *BlockMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMessageProto.Unmarshal(m, b)
}
func (m *BlockMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMessageProto.Marshal(b, m, deterministic)
}
func (m *BlockMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMessageProto.Merge(m, src)
}
func (m *BlockMessageProto) XXX_Size() int {
	return xxx_messageInfo_BlockMessageProto.Size(m)
}
func (m *BlockMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMessageProto proto.InternalMessageInfo

func (m *BlockMessageProto) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *BlockMessageProto) GetHeader() *HeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BlockMessageProto) GetBody() *BodyProto {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *BlockMessageProto) GetJustifications() []*JustificationProto {
	if m != nil {
		return m.Justifications
	}
	return nil
}

func (m *BlockMessageProto) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *BlockMessageProto) GetSeqNum() int32 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *BlockMessageProto) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *BlockMessageProto) GetSigAlgorithm() string {
	if m != nil {
		return m.SigAlgorithm
	}
	return ""
}

func (m *BlockMessageProto) GetShardId() string {
	if m != nil {
		return m.ShardId
	}
	return ""
}

func (m *BlockMessageProto) GetExtraBytes() []byte {
	if m != nil {
		return m.ExtraBytes
	}
	return nil
}

type BlockHashMessageProto struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockCreator         []byte   `protobuf:"bytes,2,opt,name=blockCreator,proto3" json:"blockCreator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHashMessageProto) Reset()         { *m = BlockHashMessageProto{} }
func (m *BlockHashMessageProto) String() string { return proto.CompactTextString(m) }
func (*BlockHashMessageProto) ProtoMessage()    {}
func (*BlockHashMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{12}
}

func (m *BlockHashMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHashMessageProto.Unmarshal(m, b)
}
func (m *BlockHashMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHashMessageProto.Marshal(b, m, deterministic)
}
func (m *BlockHashMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHashMessageProto.Merge(m, src)
}
func (m *BlockHashMessageProto) XXX_Size() int {
	return xxx_messageInfo_BlockHashMessageProto.Size(m)
}
func (m *BlockHashMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHashMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHashMessageProto proto.InternalMessageInfo

func (m *BlockHashMessageProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHashMessageProto) GetBlockCreator() []byte {
	if m != nil {
		return m.BlockCreator
	}
	return nil
}

type BlockMetadataInternal struct {
	BlockHash            []byte                `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Parents              [][]byte              `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Sender               []byte                `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Justifications       []*JustificationProto `protobuf:"bytes,4,rep,name=justifications,proto3" json:"justifications,omitempty"`
	Bonds                []*BondProto          `protobuf:"bytes,5,rep,name=bonds,proto3" json:"bonds,omitempty"`
	BlockNum             int64                 `protobuf:"varint,6,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	SeqNum               int32                 `protobuf:"varint,7,opt,name=seqNum,proto3" json:"seqNum,omitempty"`
	Invalid              bool                  `protobuf:"varint,8,opt,name=invalid,proto3" json:"invalid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockMetadataInternal) Reset()         { *m = BlockMetadataInternal{} }
func (m *BlockMetadataInternal) String() string { return proto.CompactTextString(m) }
func (*BlockMetadataInternal) ProtoMessage()    {}
func (*BlockMetadataInternal) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{13}
}

func (m *BlockMetadataInternal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadataInternal.Unmarshal(m, b)
}
func (m *BlockMetadataInternal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadataInternal.Marshal(b, m, deterministic)
}
func (m *BlockMetadataInternal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadataInternal.Merge(m, src)
}
func (m *BlockMetadataInternal) XXX_Size() int {
	return xxx_messageInfo_BlockMetadataInternal.Size(m)
}
func (m *BlockMetadataInternal) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadataInternal.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadataInternal proto.InternalMessageInfo

func (m *BlockMetadataInternal) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *BlockMetadataInternal) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *BlockMetadataInternal) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *BlockMetadataInternal) GetJustifications() []*JustificationProto {
	if m != nil {
		return m.Justifications
	}
	return nil
}

func (m *BlockMetadataInternal) GetBonds() []*BondProto {
	if m != nil {
		return m.Bonds
	}
	return nil
}

func (m *BlockMetadataInternal) GetBlockNum() int64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *BlockMetadataInternal) GetSeqNum() int32 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *BlockMetadataInternal) GetInvalid() bool {
	if m != nil {
		return m.Invalid
	}
	return false
}

type HeaderProto struct {
	ParentsHashList      [][]byte `protobuf:"bytes,1,rep,name=parentsHashList,proto3" json:"parentsHashList,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              int64    `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	ExtraBytes           []byte   `protobuf:"bytes,7,opt,name=extraBytes,proto3" json:"extraBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderProto) Reset()         { *m = HeaderProto{} }
func (m *HeaderProto) String() string { return proto.CompactTextString(m) }
func (*HeaderProto) ProtoMessage()    {}
func (*HeaderProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{14}
}

func (m *HeaderProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderProto.Unmarshal(m, b)
}
func (m *HeaderProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderProto.Marshal(b, m, deterministic)
}
func (m *HeaderProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderProto.Merge(m, src)
}
func (m *HeaderProto) XXX_Size() int {
	return xxx_messageInfo_HeaderProto.Size(m)
}
func (m *HeaderProto) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderProto.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderProto proto.InternalMessageInfo

func (m *HeaderProto) GetParentsHashList() [][]byte {
	if m != nil {
		return m.ParentsHashList
	}
	return nil
}

func (m *HeaderProto) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HeaderProto) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HeaderProto) GetExtraBytes() []byte {
	if m != nil {
		return m.ExtraBytes
	}
	return nil
}

//*
// Note: deploys are uniquely keyed by `user`, `timestamp`.
//
// **TODO**: details of signatures and payment. See RHOL-781
type DeployDataProto struct {
	Deployer              []byte   `protobuf:"bytes,1,opt,name=deployer,proto3" json:"deployer,omitempty"`
	Term                  string   `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	Timestamp             int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sig                   []byte   `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	SigAlgorithm          string   `protobuf:"bytes,5,opt,name=sigAlgorithm,proto3" json:"sigAlgorithm,omitempty"`
	PhloPrice             int64    `protobuf:"varint,7,opt,name=phloPrice,proto3" json:"phloPrice,omitempty"`
	PhloLimit             int64    `protobuf:"varint,8,opt,name=phloLimit,proto3" json:"phloLimit,omitempty"`
	ValidAfterBlockNumber int64    `protobuf:"varint,10,opt,name=validAfterBlockNumber,proto3" json:"validAfterBlockNumber,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DeployDataProto) Reset()         { *m = DeployDataProto{} }
func (m *DeployDataProto) String() string { return proto.CompactTextString(m) }
func (*DeployDataProto) ProtoMessage()    {}
func (*DeployDataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{15}
}

func (m *DeployDataProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployDataProto.Unmarshal(m, b)
}
func (m *DeployDataProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployDataProto.Marshal(b, m, deterministic)
}
func (m *DeployDataProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployDataProto.Merge(m, src)
}
func (m *DeployDataProto) XXX_Size() int {
	return xxx_messageInfo_DeployDataProto.Size(m)
}
func (m *DeployDataProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployDataProto.DiscardUnknown(m)
}

var xxx_messageInfo_DeployDataProto proto.InternalMessageInfo

func (m *DeployDataProto) GetDeployer() []byte {
	if m != nil {
		return m.Deployer
	}
	return nil
}

func (m *DeployDataProto) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *DeployDataProto) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DeployDataProto) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *DeployDataProto) GetSigAlgorithm() string {
	if m != nil {
		return m.SigAlgorithm
	}
	return ""
}

func (m *DeployDataProto) GetPhloPrice() int64 {
	if m != nil {
		return m.PhloPrice
	}
	return 0
}

func (m *DeployDataProto) GetPhloLimit() int64 {
	if m != nil {
		return m.PhloLimit
	}
	return 0
}

func (m *DeployDataProto) GetValidAfterBlockNumber() int64 {
	if m != nil {
		return m.ValidAfterBlockNumber
	}
	return 0
}

type ProcessedDeployProto struct {
	Deploy               *DeployDataProto `protobuf:"bytes,1,opt,name=deploy,proto3" json:"deploy,omitempty"`
	Cost                 *PCost           `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`
	DeployLog            []*EventProto    `protobuf:"bytes,3,rep,name=deployLog,proto3" json:"deployLog,omitempty"`
	Errored              bool             `protobuf:"varint,5,opt,name=errored,proto3" json:"errored,omitempty"`
	SystemDeployError    string           `protobuf:"bytes,6,opt,name=systemDeployError,proto3" json:"systemDeployError,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProcessedDeployProto) Reset()         { *m = ProcessedDeployProto{} }
func (m *ProcessedDeployProto) String() string { return proto.CompactTextString(m) }
func (*ProcessedDeployProto) ProtoMessage()    {}
func (*ProcessedDeployProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{16}
}

func (m *ProcessedDeployProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessedDeployProto.Unmarshal(m, b)
}
func (m *ProcessedDeployProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessedDeployProto.Marshal(b, m, deterministic)
}
func (m *ProcessedDeployProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessedDeployProto.Merge(m, src)
}
func (m *ProcessedDeployProto) XXX_Size() int {
	return xxx_messageInfo_ProcessedDeployProto.Size(m)
}
func (m *ProcessedDeployProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessedDeployProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessedDeployProto proto.InternalMessageInfo

func (m *ProcessedDeployProto) GetDeploy() *DeployDataProto {
	if m != nil {
		return m.Deploy
	}
	return nil
}

func (m *ProcessedDeployProto) GetCost() *PCost {
	if m != nil {
		return m.Cost
	}
	return nil
}

func (m *ProcessedDeployProto) GetDeployLog() []*EventProto {
	if m != nil {
		return m.DeployLog
	}
	return nil
}

func (m *ProcessedDeployProto) GetErrored() bool {
	if m != nil {
		return m.Errored
	}
	return false
}

func (m *ProcessedDeployProto) GetSystemDeployError() string {
	if m != nil {
		return m.SystemDeployError
	}
	return ""
}

type SlashSystemDeployDataProto struct {
	InvalidBlockHash     []byte   `protobuf:"bytes,1,opt,name=invalidBlockHash,proto3" json:"invalidBlockHash,omitempty"`
	IssuerPublicKey      []byte   `protobuf:"bytes,2,opt,name=issuerPublicKey,proto3" json:"issuerPublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlashSystemDeployDataProto) Reset()         { *m = SlashSystemDeployDataProto{} }
func (m *SlashSystemDeployDataProto) String() string { return proto.CompactTextString(m) }
func (*SlashSystemDeployDataProto) ProtoMessage()    {}
func (*SlashSystemDeployDataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{17}
}

func (m *SlashSystemDeployDataProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlashSystemDeployDataProto.Unmarshal(m, b)
}
func (m *SlashSystemDeployDataProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlashSystemDeployDataProto.Marshal(b, m, deterministic)
}
func (m *SlashSystemDeployDataProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashSystemDeployDataProto.Merge(m, src)
}
func (m *SlashSystemDeployDataProto) XXX_Size() int {
	return xxx_messageInfo_SlashSystemDeployDataProto.Size(m)
}
func (m *SlashSystemDeployDataProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashSystemDeployDataProto.DiscardUnknown(m)
}

var xxx_messageInfo_SlashSystemDeployDataProto proto.InternalMessageInfo

func (m *SlashSystemDeployDataProto) GetInvalidBlockHash() []byte {
	if m != nil {
		return m.InvalidBlockHash
	}
	return nil
}

func (m *SlashSystemDeployDataProto) GetIssuerPublicKey() []byte {
	if m != nil {
		return m.IssuerPublicKey
	}
	return nil
}

type CloseBlockSystemDeployDataProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseBlockSystemDeployDataProto) Reset()         { *m = CloseBlockSystemDeployDataProto{} }
func (m *CloseBlockSystemDeployDataProto) String() string { return proto.CompactTextString(m) }
func (*CloseBlockSystemDeployDataProto) ProtoMessage()    {}
func (*CloseBlockSystemDeployDataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{18}
}

func (m *CloseBlockSystemDeployDataProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseBlockSystemDeployDataProto.Unmarshal(m, b)
}
func (m *CloseBlockSystemDeployDataProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseBlockSystemDeployDataProto.Marshal(b, m, deterministic)
}
func (m *CloseBlockSystemDeployDataProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseBlockSystemDeployDataProto.Merge(m, src)
}
func (m *CloseBlockSystemDeployDataProto) XXX_Size() int {
	return xxx_messageInfo_CloseBlockSystemDeployDataProto.Size(m)
}
func (m *CloseBlockSystemDeployDataProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseBlockSystemDeployDataProto.DiscardUnknown(m)
}

var xxx_messageInfo_CloseBlockSystemDeployDataProto proto.InternalMessageInfo

type SystemDeployDataProto struct {
	// Types that are valid to be assigned to SystemDeploy:
	//	*SystemDeployDataProto_SlashSystemDeploy
	//	*SystemDeployDataProto_CloseBlockSystemDeploy
	SystemDeploy         isSystemDeployDataProto_SystemDeploy `protobuf_oneof:"systemDeploy"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *SystemDeployDataProto) Reset()         { *m = SystemDeployDataProto{} }
func (m *SystemDeployDataProto) String() string { return proto.CompactTextString(m) }
func (*SystemDeployDataProto) ProtoMessage()    {}
func (*SystemDeployDataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{19}
}

func (m *SystemDeployDataProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemDeployDataProto.Unmarshal(m, b)
}
func (m *SystemDeployDataProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemDeployDataProto.Marshal(b, m, deterministic)
}
func (m *SystemDeployDataProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemDeployDataProto.Merge(m, src)
}
func (m *SystemDeployDataProto) XXX_Size() int {
	return xxx_messageInfo_SystemDeployDataProto.Size(m)
}
func (m *SystemDeployDataProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemDeployDataProto.DiscardUnknown(m)
}

var xxx_messageInfo_SystemDeployDataProto proto.InternalMessageInfo

type isSystemDeployDataProto_SystemDeploy interface {
	isSystemDeployDataProto_SystemDeploy()
}

type SystemDeployDataProto_SlashSystemDeploy struct {
	SlashSystemDeploy *SlashSystemDeployDataProto `protobuf:"bytes,1,opt,name=slashSystemDeploy,proto3,oneof"`
}

type SystemDeployDataProto_CloseBlockSystemDeploy struct {
	CloseBlockSystemDeploy *CloseBlockSystemDeployDataProto `protobuf:"bytes,2,opt,name=closeBlockSystemDeploy,proto3,oneof"`
}

func (*SystemDeployDataProto_SlashSystemDeploy) isSystemDeployDataProto_SystemDeploy() {}

func (*SystemDeployDataProto_CloseBlockSystemDeploy) isSystemDeployDataProto_SystemDeploy() {}

func (m *SystemDeployDataProto) GetSystemDeploy() isSystemDeployDataProto_SystemDeploy {
	if m != nil {
		return m.SystemDeploy
	}
	return nil
}

func (m *SystemDeployDataProto) GetSlashSystemDeploy() *SlashSystemDeployDataProto {
	if x, ok := m.GetSystemDeploy().(*SystemDeployDataProto_SlashSystemDeploy); ok {
		return x.SlashSystemDeploy
	}
	return nil
}

func (m *SystemDeployDataProto) GetCloseBlockSystemDeploy() *CloseBlockSystemDeployDataProto {
	if x, ok := m.GetSystemDeploy().(*SystemDeployDataProto_CloseBlockSystemDeploy); ok {
		return x.CloseBlockSystemDeploy
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SystemDeployDataProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SystemDeployDataProto_SlashSystemDeploy)(nil),
		(*SystemDeployDataProto_CloseBlockSystemDeploy)(nil),
	}
}

type ProcessedSystemDeployProto struct {
	SystemDeploy         *SystemDeployDataProto `protobuf:"bytes,1,opt,name=systemDeploy,proto3" json:"systemDeploy,omitempty"`
	DeployLog            []*EventProto          `protobuf:"bytes,2,rep,name=deployLog,proto3" json:"deployLog,omitempty"`
	ErrorMsg             string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProcessedSystemDeployProto) Reset()         { *m = ProcessedSystemDeployProto{} }
func (m *ProcessedSystemDeployProto) String() string { return proto.CompactTextString(m) }
func (*ProcessedSystemDeployProto) ProtoMessage()    {}
func (*ProcessedSystemDeployProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{20}
}

func (m *ProcessedSystemDeployProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessedSystemDeployProto.Unmarshal(m, b)
}
func (m *ProcessedSystemDeployProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessedSystemDeployProto.Marshal(b, m, deterministic)
}
func (m *ProcessedSystemDeployProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessedSystemDeployProto.Merge(m, src)
}
func (m *ProcessedSystemDeployProto) XXX_Size() int {
	return xxx_messageInfo_ProcessedSystemDeployProto.Size(m)
}
func (m *ProcessedSystemDeployProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessedSystemDeployProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessedSystemDeployProto proto.InternalMessageInfo

func (m *ProcessedSystemDeployProto) GetSystemDeploy() *SystemDeployDataProto {
	if m != nil {
		return m.SystemDeploy
	}
	return nil
}

func (m *ProcessedSystemDeployProto) GetDeployLog() []*EventProto {
	if m != nil {
		return m.DeployLog
	}
	return nil
}

func (m *ProcessedSystemDeployProto) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type BodyProto struct {
	State                *RChainStateProto             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Deploys              []*ProcessedDeployProto       `protobuf:"bytes,2,rep,name=deploys,proto3" json:"deploys,omitempty"`
	SystemDeploys        []*ProcessedSystemDeployProto `protobuf:"bytes,3,rep,name=systemDeploys,proto3" json:"systemDeploys,omitempty"`
	ExtraBytes           []byte                        `protobuf:"bytes,4,opt,name=extraBytes,proto3" json:"extraBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *BodyProto) Reset()         { *m = BodyProto{} }
func (m *BodyProto) String() string { return proto.CompactTextString(m) }
func (*BodyProto) ProtoMessage()    {}
func (*BodyProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{21}
}

func (m *BodyProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyProto.Unmarshal(m, b)
}
func (m *BodyProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyProto.Marshal(b, m, deterministic)
}
func (m *BodyProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyProto.Merge(m, src)
}
func (m *BodyProto) XXX_Size() int {
	return xxx_messageInfo_BodyProto.Size(m)
}
func (m *BodyProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyProto.DiscardUnknown(m)
}

var xxx_messageInfo_BodyProto proto.InternalMessageInfo

func (m *BodyProto) GetState() *RChainStateProto {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *BodyProto) GetDeploys() []*ProcessedDeployProto {
	if m != nil {
		return m.Deploys
	}
	return nil
}

func (m *BodyProto) GetSystemDeploys() []*ProcessedSystemDeployProto {
	if m != nil {
		return m.SystemDeploys
	}
	return nil
}

func (m *BodyProto) GetExtraBytes() []byte {
	if m != nil {
		return m.ExtraBytes
	}
	return nil
}

type JustificationProto struct {
	Validator            []byte   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	LatestBlockHash      []byte   `protobuf:"bytes,2,opt,name=latestBlockHash,proto3" json:"latestBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JustificationProto) Reset()         { *m = JustificationProto{} }
func (m *JustificationProto) String() string { return proto.CompactTextString(m) }
func (*JustificationProto) ProtoMessage()    {}
func (*JustificationProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{22}
}

func (m *JustificationProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JustificationProto.Unmarshal(m, b)
}
func (m *JustificationProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JustificationProto.Marshal(b, m, deterministic)
}
func (m *JustificationProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JustificationProto.Merge(m, src)
}
func (m *JustificationProto) XXX_Size() int {
	return xxx_messageInfo_JustificationProto.Size(m)
}
func (m *JustificationProto) XXX_DiscardUnknown() {
	xxx_messageInfo_JustificationProto.DiscardUnknown(m)
}

var xxx_messageInfo_JustificationProto proto.InternalMessageInfo

func (m *JustificationProto) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *JustificationProto) GetLatestBlockHash() []byte {
	if m != nil {
		return m.LatestBlockHash
	}
	return nil
}

type RChainStateProto struct {
	PreStateHash  []byte `protobuf:"bytes,1,opt,name=preStateHash,proto3" json:"preStateHash,omitempty"`
	PostStateHash []byte `protobuf:"bytes,2,opt,name=postStateHash,proto3" json:"postStateHash,omitempty"`
	//Internals of what will be the "blessed" PoS contract
	//(which will be part of the tuplespace in the real implementation).
	Bonds                []*BondProto `protobuf:"bytes,3,rep,name=bonds,proto3" json:"bonds,omitempty"`
	BlockNumber          int64        `protobuf:"varint,4,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RChainStateProto) Reset()         { *m = RChainStateProto{} }
func (m *RChainStateProto) String() string { return proto.CompactTextString(m) }
func (*RChainStateProto) ProtoMessage()    {}
func (*RChainStateProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{23}
}

func (m *RChainStateProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RChainStateProto.Unmarshal(m, b)
}
func (m *RChainStateProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RChainStateProto.Marshal(b, m, deterministic)
}
func (m *RChainStateProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RChainStateProto.Merge(m, src)
}
func (m *RChainStateProto) XXX_Size() int {
	return xxx_messageInfo_RChainStateProto.Size(m)
}
func (m *RChainStateProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RChainStateProto.DiscardUnknown(m)
}

var xxx_messageInfo_RChainStateProto proto.InternalMessageInfo

func (m *RChainStateProto) GetPreStateHash() []byte {
	if m != nil {
		return m.PreStateHash
	}
	return nil
}

func (m *RChainStateProto) GetPostStateHash() []byte {
	if m != nil {
		return m.PostStateHash
	}
	return nil
}

func (m *RChainStateProto) GetBonds() []*BondProto {
	if m != nil {
		return m.Bonds
	}
	return nil
}

func (m *RChainStateProto) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type EventProto struct {
	// Types that are valid to be assigned to EventInstance:
	//	*EventProto_Produce
	//	*EventProto_Consume
	//	*EventProto_Comm
	EventInstance        isEventProto_EventInstance `protobuf_oneof:"event_instance"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EventProto) Reset()         { *m = EventProto{} }
func (m *EventProto) String() string { return proto.CompactTextString(m) }
func (*EventProto) ProtoMessage()    {}
func (*EventProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{24}
}

func (m *EventProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventProto.Unmarshal(m, b)
}
func (m *EventProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventProto.Marshal(b, m, deterministic)
}
func (m *EventProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProto.Merge(m, src)
}
func (m *EventProto) XXX_Size() int {
	return xxx_messageInfo_EventProto.Size(m)
}
func (m *EventProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProto.DiscardUnknown(m)
}

var xxx_messageInfo_EventProto proto.InternalMessageInfo

type isEventProto_EventInstance interface {
	isEventProto_EventInstance()
}

type EventProto_Produce struct {
	Produce *ProduceEventProto `protobuf:"bytes,1,opt,name=produce,proto3,oneof"`
}

type EventProto_Consume struct {
	Consume *ConsumeEventProto `protobuf:"bytes,2,opt,name=consume,proto3,oneof"`
}

type EventProto_Comm struct {
	Comm *CommEventProto `protobuf:"bytes,3,opt,name=comm,proto3,oneof"`
}

func (*EventProto_Produce) isEventProto_EventInstance() {}

func (*EventProto_Consume) isEventProto_EventInstance() {}

func (*EventProto_Comm) isEventProto_EventInstance() {}

func (m *EventProto) GetEventInstance() isEventProto_EventInstance {
	if m != nil {
		return m.EventInstance
	}
	return nil
}

func (m *EventProto) GetProduce() *ProduceEventProto {
	if x, ok := m.GetEventInstance().(*EventProto_Produce); ok {
		return x.Produce
	}
	return nil
}

func (m *EventProto) GetConsume() *ConsumeEventProto {
	if x, ok := m.GetEventInstance().(*EventProto_Consume); ok {
		return x.Consume
	}
	return nil
}

func (m *EventProto) GetComm() *CommEventProto {
	if x, ok := m.GetEventInstance().(*EventProto_Comm); ok {
		return x.Comm
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventProto_Produce)(nil),
		(*EventProto_Consume)(nil),
		(*EventProto_Comm)(nil),
	}
}

type ProduceEventProto struct {
	ChannelsHash         []byte   `protobuf:"bytes,1,opt,name=channelsHash,proto3" json:"channelsHash,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Persistent           bool     `protobuf:"varint,3,opt,name=persistent,proto3" json:"persistent,omitempty"`
	TimesRepeated        int32    `protobuf:"varint,4,opt,name=timesRepeated,proto3" json:"timesRepeated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceEventProto) Reset()         { *m = ProduceEventProto{} }
func (m *ProduceEventProto) String() string { return proto.CompactTextString(m) }
func (*ProduceEventProto) ProtoMessage()    {}
func (*ProduceEventProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{25}
}

func (m *ProduceEventProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceEventProto.Unmarshal(m, b)
}
func (m *ProduceEventProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceEventProto.Marshal(b, m, deterministic)
}
func (m *ProduceEventProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceEventProto.Merge(m, src)
}
func (m *ProduceEventProto) XXX_Size() int {
	return xxx_messageInfo_ProduceEventProto.Size(m)
}
func (m *ProduceEventProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceEventProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceEventProto proto.InternalMessageInfo

func (m *ProduceEventProto) GetChannelsHash() []byte {
	if m != nil {
		return m.ChannelsHash
	}
	return nil
}

func (m *ProduceEventProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ProduceEventProto) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

func (m *ProduceEventProto) GetTimesRepeated() int32 {
	if m != nil {
		return m.TimesRepeated
	}
	return 0
}

type ConsumeEventProto struct {
	ChannelsHashes       [][]byte `protobuf:"bytes,1,rep,name=channelsHashes,proto3" json:"channelsHashes,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Persistent           bool     `protobuf:"varint,3,opt,name=persistent,proto3" json:"persistent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeEventProto) Reset()         { *m = ConsumeEventProto{} }
func (m *ConsumeEventProto) String() string { return proto.CompactTextString(m) }
func (*ConsumeEventProto) ProtoMessage()    {}
func (*ConsumeEventProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{26}
}

func (m *ConsumeEventProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeEventProto.Unmarshal(m, b)
}
func (m *ConsumeEventProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeEventProto.Marshal(b, m, deterministic)
}
func (m *ConsumeEventProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeEventProto.Merge(m, src)
}
func (m *ConsumeEventProto) XXX_Size() int {
	return xxx_messageInfo_ConsumeEventProto.Size(m)
}
func (m *ConsumeEventProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeEventProto.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeEventProto proto.InternalMessageInfo

func (m *ConsumeEventProto) GetChannelsHashes() [][]byte {
	if m != nil {
		return m.ChannelsHashes
	}
	return nil
}

func (m *ConsumeEventProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ConsumeEventProto) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

type CommEventProto struct {
	Consume              *ConsumeEventProto   `protobuf:"bytes,1,opt,name=consume,proto3" json:"consume,omitempty"`
	Produces             []*ProduceEventProto `protobuf:"bytes,2,rep,name=produces,proto3" json:"produces,omitempty"`
	Peeks                []*PeekProto         `protobuf:"bytes,3,rep,name=peeks,proto3" json:"peeks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommEventProto) Reset()         { *m = CommEventProto{} }
func (m *CommEventProto) String() string { return proto.CompactTextString(m) }
func (*CommEventProto) ProtoMessage()    {}
func (*CommEventProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{27}
}

func (m *CommEventProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommEventProto.Unmarshal(m, b)
}
func (m *CommEventProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommEventProto.Marshal(b, m, deterministic)
}
func (m *CommEventProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommEventProto.Merge(m, src)
}
func (m *CommEventProto) XXX_Size() int {
	return xxx_messageInfo_CommEventProto.Size(m)
}
func (m *CommEventProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CommEventProto.DiscardUnknown(m)
}

var xxx_messageInfo_CommEventProto proto.InternalMessageInfo

func (m *CommEventProto) GetConsume() *ConsumeEventProto {
	if m != nil {
		return m.Consume
	}
	return nil
}

func (m *CommEventProto) GetProduces() []*ProduceEventProto {
	if m != nil {
		return m.Produces
	}
	return nil
}

func (m *CommEventProto) GetPeeks() []*PeekProto {
	if m != nil {
		return m.Peeks
	}
	return nil
}

type PeekProto struct {
	ChannelIndex         int32    `protobuf:"varint,1,opt,name=channelIndex,proto3" json:"channelIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeekProto) Reset()         { *m = PeekProto{} }
func (m *PeekProto) String() string { return proto.CompactTextString(m) }
func (*PeekProto) ProtoMessage()    {}
func (*PeekProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{28}
}

func (m *PeekProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeekProto.Unmarshal(m, b)
}
func (m *PeekProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeekProto.Marshal(b, m, deterministic)
}
func (m *PeekProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeekProto.Merge(m, src)
}
func (m *PeekProto) XXX_Size() int {
	return xxx_messageInfo_PeekProto.Size(m)
}
func (m *PeekProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PeekProto.DiscardUnknown(m)
}

var xxx_messageInfo_PeekProto proto.InternalMessageInfo

func (m *PeekProto) GetChannelIndex() int32 {
	if m != nil {
		return m.ChannelIndex
	}
	return 0
}

type BondProto struct {
	Validator            []byte   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Stake                int64    `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BondProto) Reset()         { *m = BondProto{} }
func (m *BondProto) String() string { return proto.CompactTextString(m) }
func (*BondProto) ProtoMessage()    {}
func (*BondProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{29}
}

func (m *BondProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BondProto.Unmarshal(m, b)
}
func (m *BondProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BondProto.Marshal(b, m, deterministic)
}
func (m *BondProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BondProto.Merge(m, src)
}
func (m *BondProto) XXX_Size() int {
	return xxx_messageInfo_BondProto.Size(m)
}
func (m *BondProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BondProto.DiscardUnknown(m)
}

var xxx_messageInfo_BondProto proto.InternalMessageInfo

func (m *BondProto) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *BondProto) GetStake() int64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

type StoreNodeKeyProto struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreNodeKeyProto) Reset()         { *m = StoreNodeKeyProto{} }
func (m *StoreNodeKeyProto) String() string { return proto.CompactTextString(m) }
func (*StoreNodeKeyProto) ProtoMessage()    {}
func (*StoreNodeKeyProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{30}
}

func (m *StoreNodeKeyProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreNodeKeyProto.Unmarshal(m, b)
}
func (m *StoreNodeKeyProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreNodeKeyProto.Marshal(b, m, deterministic)
}
func (m *StoreNodeKeyProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreNodeKeyProto.Merge(m, src)
}
func (m *StoreNodeKeyProto) XXX_Size() int {
	return xxx_messageInfo_StoreNodeKeyProto.Size(m)
}
func (m *StoreNodeKeyProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreNodeKeyProto.DiscardUnknown(m)
}

var xxx_messageInfo_StoreNodeKeyProto proto.InternalMessageInfo

func (m *StoreNodeKeyProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *StoreNodeKeyProto) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type StoreItemsMessageRequestProto struct {
	StartPath            []*StoreNodeKeyProto `protobuf:"bytes,1,rep,name=startPath,proto3" json:"startPath,omitempty"`
	Skip                 int32                `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 int32                `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StoreItemsMessageRequestProto) Reset()         { *m = StoreItemsMessageRequestProto{} }
func (m *StoreItemsMessageRequestProto) String() string { return proto.CompactTextString(m) }
func (*StoreItemsMessageRequestProto) ProtoMessage()    {}
func (*StoreItemsMessageRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{31}
}

func (m *StoreItemsMessageRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreItemsMessageRequestProto.Unmarshal(m, b)
}
func (m *StoreItemsMessageRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreItemsMessageRequestProto.Marshal(b, m, deterministic)
}
func (m *StoreItemsMessageRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreItemsMessageRequestProto.Merge(m, src)
}
func (m *StoreItemsMessageRequestProto) XXX_Size() int {
	return xxx_messageInfo_StoreItemsMessageRequestProto.Size(m)
}
func (m *StoreItemsMessageRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreItemsMessageRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_StoreItemsMessageRequestProto proto.InternalMessageInfo

func (m *StoreItemsMessageRequestProto) GetStartPath() []*StoreNodeKeyProto {
	if m != nil {
		return m.StartPath
	}
	return nil
}

func (m *StoreItemsMessageRequestProto) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *StoreItemsMessageRequestProto) GetTake() int32 {
	if m != nil {
		return m.Take
	}
	return 0
}

type StoreItemProto struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreItemProto) Reset()         { *m = StoreItemProto{} }
func (m *StoreItemProto) String() string { return proto.CompactTextString(m) }
func (*StoreItemProto) ProtoMessage()    {}
func (*StoreItemProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{32}
}

func (m *StoreItemProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreItemProto.Unmarshal(m, b)
}
func (m *StoreItemProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreItemProto.Marshal(b, m, deterministic)
}
func (m *StoreItemProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreItemProto.Merge(m, src)
}
func (m *StoreItemProto) XXX_Size() int {
	return xxx_messageInfo_StoreItemProto.Size(m)
}
func (m *StoreItemProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreItemProto.DiscardUnknown(m)
}

var xxx_messageInfo_StoreItemProto proto.InternalMessageInfo

func (m *StoreItemProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *StoreItemProto) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StoreItemsMessageProto struct {
	StartPath            []*StoreNodeKeyProto `protobuf:"bytes,1,rep,name=startPath,proto3" json:"startPath,omitempty"`
	LastPath             []*StoreNodeKeyProto `protobuf:"bytes,2,rep,name=lastPath,proto3" json:"lastPath,omitempty"`
	HistoryItems         []*StoreItemProto    `protobuf:"bytes,3,rep,name=historyItems,proto3" json:"historyItems,omitempty"`
	DataItems            []*StoreItemProto    `protobuf:"bytes,4,rep,name=dataItems,proto3" json:"dataItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StoreItemsMessageProto) Reset()         { *m = StoreItemsMessageProto{} }
func (m *StoreItemsMessageProto) String() string { return proto.CompactTextString(m) }
func (*StoreItemsMessageProto) ProtoMessage()    {}
func (*StoreItemsMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6214125db808cffc, []int{33}
}

func (m *StoreItemsMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreItemsMessageProto.Unmarshal(m, b)
}
func (m *StoreItemsMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreItemsMessageProto.Marshal(b, m, deterministic)
}
func (m *StoreItemsMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreItemsMessageProto.Merge(m, src)
}
func (m *StoreItemsMessageProto) XXX_Size() int {
	return xxx_messageInfo_StoreItemsMessageProto.Size(m)
}
func (m *StoreItemsMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreItemsMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_StoreItemsMessageProto proto.InternalMessageInfo

func (m *StoreItemsMessageProto) GetStartPath() []*StoreNodeKeyProto {
	if m != nil {
		return m.StartPath
	}
	return nil
}

func (m *StoreItemsMessageProto) GetLastPath() []*StoreNodeKeyProto {
	if m != nil {
		return m.LastPath
	}
	return nil
}

func (m *StoreItemsMessageProto) GetHistoryItems() []*StoreItemProto {
	if m != nil {
		return m.HistoryItems
	}
	return nil
}

func (m *StoreItemsMessageProto) GetDataItems() []*StoreItemProto {
	if m != nil {
		return m.DataItems
	}
	return nil
}

func init() {
	proto.RegisterType((*HasBlockRequestProto)(nil), "casper.HasBlockRequestProto")
	proto.RegisterType((*HasBlockProto)(nil), "casper.HasBlockProto")
	proto.RegisterType((*BlockRequestProto)(nil), "casper.BlockRequestProto")
	proto.RegisterType((*ForkChoiceTipRequestProto)(nil), "casper.ForkChoiceTipRequestProto")
	proto.RegisterType((*ApprovedBlockCandidateProto)(nil), "casper.ApprovedBlockCandidateProto")
	proto.RegisterType((*UnapprovedBlockProto)(nil), "casper.UnapprovedBlockProto")
	proto.RegisterType((*Signature)(nil), "casper.Signature")
	proto.RegisterType((*BlockApprovalProto)(nil), "casper.BlockApprovalProto")
	proto.RegisterType((*ApprovedBlockProto)(nil), "casper.ApprovedBlockProto")
	proto.RegisterType((*ApprovedBlockRequestProto)(nil), "casper.ApprovedBlockRequestProto")
	proto.RegisterType((*NoApprovedBlockAvailableProto)(nil), "casper.NoApprovedBlockAvailableProto")
	proto.RegisterType((*BlockMessageProto)(nil), "casper.BlockMessageProto")
	proto.RegisterType((*BlockHashMessageProto)(nil), "casper.BlockHashMessageProto")
	proto.RegisterType((*BlockMetadataInternal)(nil), "casper.BlockMetadataInternal")
	proto.RegisterType((*HeaderProto)(nil), "casper.HeaderProto")
	proto.RegisterType((*DeployDataProto)(nil), "casper.DeployDataProto")
	proto.RegisterType((*ProcessedDeployProto)(nil), "casper.ProcessedDeployProto")
	proto.RegisterType((*SlashSystemDeployDataProto)(nil), "casper.SlashSystemDeployDataProto")
	proto.RegisterType((*CloseBlockSystemDeployDataProto)(nil), "casper.CloseBlockSystemDeployDataProto")
	proto.RegisterType((*SystemDeployDataProto)(nil), "casper.SystemDeployDataProto")
	proto.RegisterType((*ProcessedSystemDeployProto)(nil), "casper.ProcessedSystemDeployProto")
	proto.RegisterType((*BodyProto)(nil), "casper.BodyProto")
	proto.RegisterType((*JustificationProto)(nil), "casper.JustificationProto")
	proto.RegisterType((*RChainStateProto)(nil), "casper.RChainStateProto")
	proto.RegisterType((*EventProto)(nil), "casper.EventProto")
	proto.RegisterType((*ProduceEventProto)(nil), "casper.ProduceEventProto")
	proto.RegisterType((*ConsumeEventProto)(nil), "casper.ConsumeEventProto")
	proto.RegisterType((*CommEventProto)(nil), "casper.CommEventProto")
	proto.RegisterType((*PeekProto)(nil), "casper.PeekProto")
	proto.RegisterType((*BondProto)(nil), "casper.BondProto")
	proto.RegisterType((*StoreNodeKeyProto)(nil), "casper.StoreNodeKeyProto")
	proto.RegisterType((*StoreItemsMessageRequestProto)(nil), "casper.StoreItemsMessageRequestProto")
	proto.RegisterType((*StoreItemProto)(nil), "casper.StoreItemProto")
	proto.RegisterType((*StoreItemsMessageProto)(nil), "casper.StoreItemsMessageProto")
}

func init() { proto.RegisterFile("CasperMessage.proto", fileDescriptor_6214125db808cffc) }

var fileDescriptor_6214125db808cffc = []byte{
	// 1736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x6e, 0x24, 0x47,
	0x15, 0xde, 0xf6, 0x78, 0x3c, 0x33, 0x67, 0x1d, 0xc7, 0xee, 0x78, 0x9d, 0xd9, 0xd9, 0xec, 0xc6,
	0x74, 0x08, 0x59, 0x41, 0x34, 0x8b, 0xf2, 0x83, 0xa2, 0x08, 0x64, 0x3c, 0xb3, 0x21, 0x36, 0xd9,
	0x5d, 0x59, 0xe5, 0x8d, 0x10, 0x08, 0x09, 0xd5, 0x74, 0x9f, 0x78, 0x1a, 0xf7, 0x74, 0xf5, 0x56,
	0xd5, 0x58, 0x99, 0x1b, 0x2e, 0xb8, 0xe1, 0x82, 0x0b, 0x84, 0x10, 0xe2, 0x09, 0x10, 0x42, 0x82,
	0x07, 0x80, 0x77, 0x81, 0x8b, 0x7d, 0x12, 0x54, 0xa7, 0xaa, 0xff, 0x66, 0xa6, 0xf1, 0x92, 0x25,
	0x57, 0x9e, 0xfa, 0xaa, 0xce, 0x39, 0x5f, 0x9d, 0xdf, 0x6a, 0xc3, 0x6b, 0x63, 0xae, 0x32, 0x94,
	0x8f, 0x51, 0x29, 0x7e, 0x81, 0xc3, 0x4c, 0x0a, 0x2d, 0xfc, 0xad, 0x90, 0xc0, 0xc1, 0x2d, 0x15,
	0xf2, 0x84, 0x67, 0x93, 0x07, 0xee, 0xaf, 0xdd, 0x1e, 0xec, 0xb0, 0xa9, 0x78, 0xba, 0xc8, 0x50,
	0xd9, 0x75, 0x30, 0x86, 0xfd, 0x13, 0xae, 0x46, 0x89, 0x08, 0x2f, 0x19, 0x3e, 0x9b, 0xa3, 0xd2,
	0x67, 0xa4, 0xc6, 0x87, 0xcd, 0x29, 0x57, 0xd3, 0xbe, 0x77, 0xe8, 0xdd, 0xdf, 0x66, 0xf4, 0xfb,
	0xe3, 0xd7, 0x9f, 0x1f, 0xed, 0x83, 0x5f, 0x33, 0x4a, 0x87, 0x83, 0xef, 0xc3, 0x2b, 0xb9, 0x92,
	0xaf, 0x20, 0xfd, 0x43, 0xd8, 0x7b, 0x49, 0xfb, 0x1f, 0xc0, 0xed, 0x1f, 0x09, 0x79, 0x39, 0x9e,
	0x8a, 0x38, 0xc4, 0xa7, 0x71, 0x56, 0xd5, 0xd4, 0x2c, 0xf5, 0x5b, 0x0f, 0xee, 0x1c, 0x67, 0x99,
	0x14, 0x57, 0x18, 0x11, 0x81, 0x31, 0x4f, 0xa3, 0x38, 0xe2, 0xda, 0xee, 0xfb, 0x0f, 0xa0, 0x3d,
	0x31, 0x30, 0x71, 0xb8, 0xf9, 0xde, 0xed, 0xa1, 0xf5, 0xec, 0x90, 0xce, 0x56, 0x35, 0x31, 0x7b,
	0xce, 0x0f, 0x60, 0x5b, 0xe2, 0xb3, 0x79, 0x2c, 0x31, 0x3a, 0x8f, 0x2f, 0x54, 0x7f, 0xe3, 0xd0,
	0xbb, 0xdf, 0x66, 0x35, 0xac, 0x99, 0xcd, 0xdf, 0x3c, 0xd8, 0xff, 0x3c, 0xe5, 0x55, 0x3e, 0x96,
	0xc6, 0x31, 0xf4, 0xc2, 0x9c, 0x98, 0xa3, 0xf2, 0x56, 0x4e, 0xe5, 0xbf, 0xd0, 0x67, 0xa5, 0x94,
	0xff, 0x06, 0xf4, 0x74, 0x3c, 0x43, 0xa5, 0xf9, 0x2c, 0x23, 0x56, 0x2d, 0x56, 0x02, 0xfe, 0x00,
	0xba, 0xd1, 0x5c, 0x72, 0x1d, 0x8b, 0xb4, 0xdf, 0xa2, 0xcd, 0x62, 0xdd, 0x4c, 0xf7, 0xa7, 0xd0,
	0x3b, 0x8f, 0x2f, 0x52, 0xae, 0xe7, 0x92, 0xf4, 0x67, 0xf3, 0x49, 0x12, 0x87, 0x9f, 0xe1, 0xc2,
	0x45, 0xac, 0x04, 0xcc, 0x2e, 0x4f, 0x2e, 0x84, 0x8c, 0xf5, 0x74, 0x46, 0xd6, 0x7b, 0xac, 0x04,
	0xfc, 0x5d, 0x68, 0xa9, 0xf8, 0x82, 0x0c, 0x6f, 0x33, 0xf3, 0x33, 0xf8, 0xa3, 0x07, 0x3e, 0x5d,
	0xc8, 0xde, 0x8e, 0x27, 0xff, 0x37, 0x3f, 0xbc, 0x65, 0x6d, 0x6d, 0x90, 0xf0, 0x5e, 0x2e, 0x5c,
	0xdc, 0x83, 0xcc, 0x37, 0x5f, 0xf9, 0x4f, 0x1e, 0xf8, 0xc7, 0x5f, 0x4b, 0x7c, 0xde, 0x86, 0x4d,
	0x65, 0x13, 0xa6, 0xb5, 0x9e, 0x18, 0x6d, 0x37, 0x33, 0x93, 0x70, 0xbb, 0x66, 0xa9, 0x56, 0x49,
	0xf7, 0x00, 0xe2, 0x08, 0x53, 0x1d, 0x7f, 0x11, 0xa3, 0x24, 0x82, 0x3d, 0x56, 0x41, 0x28, 0x39,
	0x64, 0x3c, 0x3b, 0xd7, 0x86, 0xbf, 0x71, 0x4d, 0x97, 0x95, 0x40, 0xb3, 0xcd, 0x5f, 0xc1, 0xdd,
	0x27, 0xa2, 0x66, 0xf5, 0xf8, 0x8a, 0xc7, 0x09, 0x9f, 0x24, 0xf8, 0x62, 0x76, 0xbf, 0x09, 0xaf,
	0xa4, 0x22, 0xc2, 0x53, 0x8b, 0xa0, 0x74, 0xa9, 0x51, 0x07, 0x9b, 0xed, 0xff, 0xba, 0xe5, 0xda,
	0x46, 0x15, 0x35, 0x97, 0xa1, 0x5a, 0x3c, 0x29, 0x7b, 0x47, 0x09, 0xf8, 0xdf, 0x81, 0xad, 0x29,
	0xf2, 0xc8, 0xd9, 0xba, 0xf9, 0xde, 0x6b, 0xb9, 0xa7, 0x4f, 0x08, 0xb5, 0x71, 0x71, 0x47, 0x4c,
	0x50, 0x26, 0x22, 0x5a, 0x50, 0x66, 0x56, 0x82, 0x32, 0x12, 0xd1, 0xc2, 0x1e, 0xa4, 0x6d, 0x7f,
	0x04, 0x3b, 0xbf, 0x9c, 0x2b, 0x73, 0xa7, 0x90, 0x4a, 0x46, 0xf5, 0x37, 0x29, 0x8a, 0x83, 0x5c,
	0xe0, 0xc7, 0xd5, 0x5d, 0x2b, 0xb9, 0x24, 0xe1, 0x1f, 0xc0, 0x96, 0xc2, 0xd4, 0xf0, 0x6a, 0x13,
	0x65, 0xb7, 0xb2, 0xf8, 0xb3, 0x27, 0xf3, 0x59, 0x7f, 0x8b, 0x5a, 0x89, 0x5b, 0xe5, 0x35, 0xd3,
	0x29, 0x6a, 0xc6, 0xb4, 0x1e, 0x15, 0x5f, 0x1c, 0x17, 0x65, 0xd6, 0x25, 0x5f, 0xd6, 0x30, 0xbf,
	0x0f, 0x1d, 0x35, 0xe5, 0x32, 0x3a, 0x8d, 0xfa, 0x3d, 0xda, 0xce, 0x97, 0x26, 0x54, 0xf8, 0xa5,
	0x96, 0x7c, 0xb4, 0xd0, 0xa8, 0xfa, 0x40, 0x6a, 0x2b, 0x48, 0x73, 0x10, 0xa6, 0x70, 0x6b, 0x94,
	0x7b, 0xb7, 0x16, 0x87, 0x35, 0xed, 0xdb, 0x70, 0xa4, 0x50, 0x8c, 0x25, 0x72, 0x2d, 0x6c, 0x0c,
	0xb6, 0x59, 0x0d, 0x6b, 0xb6, 0xf4, 0xd7, 0x96, 0x33, 0xf5, 0x18, 0x35, 0x8f, 0xb8, 0xe6, 0xa7,
	0xa9, 0x46, 0x99, 0xf2, 0xe4, 0x9a, 0x90, 0x7f, 0x04, 0x9d, 0x8c, 0x4b, 0x4c, 0xb5, 0xad, 0xae,
	0xed, 0xd1, 0xbd, 0xe7, 0x47, 0x77, 0x06, 0xb7, 0x43, 0x91, 0x24, 0x18, 0x1a, 0xef, 0x0f, 0xe3,
	0xd9, 0x6c, 0xae, 0x4d, 0xda, 0x0e, 0x1f, 0xc5, 0x4a, 0xb3, 0xfc, 0x78, 0x25, 0x28, 0xad, 0x5a,
	0x50, 0x26, 0xff, 0x7b, 0xc0, 0xaf, 0x35, 0xba, 0x9c, 0x10, 0x9f, 0x42, 0x7b, 0x22, 0xd2, 0x48,
	0xf5, 0xdb, 0xf5, 0x8e, 0x30, 0x12, 0x69, 0xf4, 0x62, 0x1a, 0xad, 0xbc, 0xe9, 0xed, 0xe4, 0x8b,
	0x3c, 0x87, 0x5a, 0xac, 0x58, 0x57, 0xb2, 0xab, 0x53, 0xcb, 0xae, 0x3e, 0x74, 0xe2, 0xf4, 0x8a,
	0x27, 0x71, 0x44, 0x69, 0xd4, 0x65, 0xf9, 0xf2, 0xe3, 0xb7, 0x9f, 0x1f, 0x05, 0xc1, 0x61, 0x28,
	0x44, 0x36, 0x94, 0xe1, 0x94, 0xc7, 0xe9, 0x70, 0x26, 0x22, 0x4c, 0xd4, 0xb0, 0x16, 0x99, 0xe0,
	0x77, 0x1e, 0xdc, 0xac, 0x54, 0x94, 0x7f, 0x1f, 0x5e, 0x75, 0x4e, 0x35, 0x21, 0x31, 0xf4, 0xfa,
	0x9e, 0x89, 0x05, 0x5b, 0x86, 0xeb, 0x83, 0xaa, 0xbd, 0x3c, 0xa8, 0xfa, 0xd0, 0xb9, 0x42, 0xa9,
	0xcc, 0x9c, 0xb2, 0x77, 0xc9, 0x97, 0x4b, 0x09, 0xdc, 0x59, 0x4e, 0xe0, 0xe0, 0x37, 0x1b, 0xf0,
	0xea, 0x43, 0xcc, 0x12, 0xb1, 0x78, 0xc8, 0x35, 0xb7, 0xac, 0xcc, 0xd8, 0x23, 0xc8, 0x75, 0xa7,
	0x6d, 0x56, 0xac, 0x4d, 0xfa, 0x6a, 0x94, 0xf9, 0xb4, 0xa2, 0xdf, 0x75, 0x6e, 0xad, 0x65, 0x6e,
	0xae, 0x24, 0x37, 0x9b, 0x4b, 0xb2, 0xbd, 0xa6, 0x24, 0xcd, 0xe0, 0x9c, 0x26, 0xe2, 0x4c, 0xc6,
	0x21, 0x12, 0xed, 0x16, 0x2b, 0x81, 0x7c, 0xf7, 0x51, 0x3c, 0x8b, 0x35, 0x85, 0xc2, 0xed, 0x12,
	0xe0, 0x7f, 0x00, 0xb7, 0x28, 0x2a, 0xc7, 0x5f, 0x68, 0x94, 0x23, 0x17, 0xd4, 0x09, 0x4a, 0xaa,
	0xdf, 0x16, 0x5b, 0xbf, 0x19, 0xfc, 0xcb, 0x83, 0xfd, 0x33, 0x29, 0x42, 0x54, 0x0a, 0x23, 0xeb,
	0x92, 0xfc, 0xb5, 0xb3, 0x65, 0xaf, 0xef, 0x66, 0xd8, 0xeb, 0x79, 0xce, 0x2d, 0xf9, 0x8d, 0xb9,
	0x63, 0xfe, 0x00, 0x36, 0x43, 0xa1, 0xb4, 0x6b, 0xa5, 0x5b, 0xc3, 0xb3, 0xb1, 0x50, 0x9a, 0x11,
	0xe6, 0x7f, 0x17, 0x7a, 0xf6, 0xd4, 0x23, 0x61, 0x46, 0xbb, 0xc9, 0x61, 0x3f, 0xd7, 0xf7, 0xc9,
	0x15, 0xa6, 0xda, 0x8d, 0xc0, 0xe2, 0x90, 0x89, 0x2d, 0x4a, 0x29, 0x24, 0x46, 0xe4, 0xa8, 0x2e,
	0xcb, 0x97, 0xfe, 0xbb, 0xb0, 0xa7, 0x16, 0x4a, 0xe3, 0xcc, 0x12, 0xf9, 0xc4, 0xc0, 0x14, 0xff,
	0x1e, 0x5b, 0xdd, 0x08, 0x24, 0x0c, 0xce, 0x13, 0xae, 0xa6, 0xe7, 0x95, 0x9d, 0x32, 0xe6, 0xdf,
	0x86, 0x5d, 0x97, 0xcb, 0xa3, 0xa5, 0x96, 0xb1, 0x82, 0x9b, 0xac, 0x8d, 0x95, 0x9a, 0xa3, 0x3c,
	0x2b, 0x9e, 0x36, 0xb6, 0x63, 0x2d, 0xc3, 0xc1, 0x37, 0xe0, 0xcd, 0x71, 0x22, 0x14, 0x92, 0xec,
	0x5a, 0xc3, 0xc1, 0xbf, 0x3d, 0xb8, 0xb5, 0x9e, 0x12, 0x83, 0x3d, 0xb5, 0x4c, 0xd8, 0x85, 0x20,
	0x28, 0x1e, 0x02, 0x8d, 0x37, 0x3a, 0xb9, 0xc1, 0x56, 0xc5, 0x7d, 0x0e, 0x07, 0xe1, 0x5a, 0x42,
	0x2e, 0x58, 0xef, 0xe4, 0x8a, 0xaf, 0xa1, 0x7d, 0x72, 0x83, 0x35, 0x28, 0x1a, 0xed, 0xc0, 0x76,
	0xd5, 0xf9, 0xc1, 0xdf, 0x3d, 0x18, 0x14, 0x79, 0x55, 0x3d, 0x99, 0x3f, 0x92, 0x6a, 0xc7, 0xdd,
	0x05, 0xef, 0x16, 0x17, 0x5c, 0x67, 0x9d, 0xd5, 0x44, 0xea, 0x39, 0xb5, 0xf1, 0x22, 0x39, 0x35,
	0x80, 0x2e, 0x25, 0xd1, 0x63, 0x65, 0xdf, 0x97, 0x3d, 0x56, 0xac, 0x4d, 0x1d, 0xf4, 0x8a, 0x51,
	0xee, 0x0f, 0xa1, 0xad, 0x74, 0xf9, 0x7e, 0xeb, 0xe7, 0x7a, 0xd9, 0xd8, 0x74, 0x39, 0x7a, 0x09,
	0xb9, 0x97, 0x3e, 0x1d, 0xf3, 0xbf, 0x07, 0x1d, 0x6b, 0x26, 0x7f, 0xb3, 0xbd, 0x91, 0x4b, 0xac,
	0xab, 0x2d, 0x96, 0x1f, 0xf6, 0x4f, 0xe0, 0x95, 0xea, 0x9d, 0x94, 0xab, 0x8d, 0x60, 0x45, 0x7a,
	0xc5, 0x83, 0xac, 0x2e, 0xb8, 0xd4, 0xf1, 0x36, 0x57, 0x3a, 0xde, 0xcf, 0xc1, 0x5f, 0x9d, 0x43,
	0xa6, 0xa3, 0x50, 0x96, 0xd3, 0xfc, 0x75, 0xb3, 0xb2, 0x00, 0x4c, 0xc6, 0x27, 0x5c, 0xa3, 0xd2,
	0x65, 0x71, 0xb8, 0x8c, 0x5f, 0x82, 0x83, 0xbf, 0x78, 0xb0, 0xbb, 0xec, 0x1b, 0xd3, 0xf0, 0x32,
	0x89, 0x04, 0x54, 0x0a, 0xab, 0x86, 0x99, 0x47, 0x5f, 0x26, 0x94, 0x2e, 0x0f, 0x59, 0x03, 0x75,
	0xd0, 0x7f, 0x27, 0x1f, 0x7f, 0xad, 0x86, 0xf1, 0x97, 0x8f, 0xb7, 0x43, 0xb8, 0x39, 0xa9, 0x74,
	0xbe, 0x4d, 0xea, 0x7c, 0x55, 0x28, 0xf8, 0xa7, 0x07, 0x50, 0x66, 0x87, 0xff, 0x21, 0x74, 0x32,
	0x29, 0xa2, 0x79, 0x88, 0xcb, 0x5f, 0x75, 0x67, 0x16, 0x2e, 0xcf, 0x9e, 0xdc, 0x60, 0xf9, 0x59,
	0x23, 0x16, 0x8a, 0x54, 0xcd, 0x67, 0xe8, 0x2a, 0xa8, 0x10, 0x1b, 0x5b, 0xb8, 0x2e, 0xe6, 0xce,
	0xfa, 0xef, 0x9a, 0x16, 0x39, 0x9b, 0xb9, 0x27, 0xe4, 0x41, 0x29, 0x33, 0x9b, 0xd5, 0x04, 0xe8,
	0xd4, 0x68, 0x17, 0x76, 0xd0, 0xa0, 0xbf, 0x88, 0x53, 0xa5, 0x79, 0x1a, 0x62, 0xf0, 0x7b, 0x0f,
	0xf6, 0x56, 0x78, 0x19, 0x3f, 0x87, 0x53, 0x9e, 0xa6, 0x98, 0xa8, 0xaa, 0x9f, 0xab, 0x58, 0xf1,
	0xfe, 0xda, 0xa8, 0xbc, 0xbf, 0xee, 0x01, 0x64, 0x66, 0x5e, 0x2a, 0x8d, 0xa9, 0x26, 0x4e, 0x5d,
	0x56, 0x41, 0x4c, 0x6c, 0x68, 0x9e, 0x31, 0xcc, 0x90, 0x6b, 0x8c, 0xc8, 0x9d, 0x6d, 0x56, 0x07,
	0x03, 0x01, 0x7b, 0x2b, 0x77, 0xf6, 0xbf, 0x05, 0x3b, 0x55, 0xf3, 0xa8, 0xdc, 0x80, 0x5f, 0x42,
	0xbf, 0x0a, 0xad, 0xe0, 0xcf, 0x1e, 0xec, 0xd4, 0x3d, 0xe6, 0xbf, 0x5f, 0x86, 0xc3, 0xbb, 0x26,
	0x1c, 0x65, 0x30, 0x3e, 0x84, 0xae, 0x0b, 0x67, 0x5e, 0xb4, 0xcd, 0xb1, 0x67, 0xc5, 0x51, 0x93,
	0x8b, 0x19, 0xe2, 0xe5, 0x4a, 0x2e, 0x9e, 0x21, 0x5e, 0xba, 0x5c, 0xa4, 0xfd, 0xe0, 0x01, 0xf4,
	0x0a, 0xac, 0x12, 0xa3, 0xd3, 0x34, 0xc2, 0x2f, 0x89, 0x66, 0x9b, 0xd5, 0xb0, 0xe0, 0xc8, 0x74,
	0x20, 0x97, 0xd0, 0xd7, 0x54, 0xe6, 0x3e, 0xf5, 0xa7, 0x4b, 0x74, 0x1f, 0xef, 0x76, 0x11, 0xfc,
	0x00, 0xf6, 0xce, 0xb5, 0x90, 0xf8, 0x44, 0x44, 0xf8, 0x19, 0x2e, 0x9a, 0x5f, 0xde, 0xfb, 0xd0,
	0x8e, 0x89, 0x86, 0xfd, 0x8f, 0x84, 0x5d, 0x04, 0xff, 0xf0, 0xe0, 0x2e, 0xc9, 0x9f, 0x6a, 0x9c,
	0x29, 0xf7, 0xda, 0xae, 0x7d, 0x3a, 0xfe, 0x04, 0x7a, 0x4a, 0x73, 0xa9, 0xcf, 0xb8, 0x9e, 0x52,
	0x44, 0x2b, 0x3e, 0x5b, 0xb1, 0x7c, 0xed, 0x93, 0xb4, 0xd4, 0x65, 0x48, 0xaa, 0xcb, 0x38, 0x73,
	0x7c, 0xe8, 0x37, 0xbd, 0xb9, 0xcc, 0x15, 0x5b, 0x16, 0x33, 0xbf, 0x9b, 0x3f, 0x07, 0x3e, 0x82,
	0x9d, 0x82, 0xba, 0xe5, 0xba, 0x0b, 0xad, 0xcb, 0xe2, 0xbf, 0x0f, 0xe6, 0xa7, 0xb9, 0xf5, 0x15,
	0x4f, 0xe6, 0xe8, 0xb2, 0xcd, 0x2e, 0x82, 0x3f, 0xb4, 0xe0, 0x60, 0xe5, 0xd6, 0x5f, 0xf3, 0x75,
	0x3f, 0x87, 0x6e, 0xc2, 0x95, 0xd5, 0xbb, 0xf1, 0xb2, 0x7a, 0x0b, 0x55, 0xfe, 0xcf, 0x60, 0x7b,
	0x1a, 0x2b, 0x2d, 0xe4, 0x82, 0xee, 0xe2, 0x32, 0xf4, 0xa0, 0xa6, 0xba, 0x70, 0xd0, 0xb5, 0x7a,
	0x6b, 0xba, 0xfc, 0xa7, 0xd0, 0xa3, 0xaf, 0x2c, 0x52, 0xbc, 0xf9, 0x52, 0x8a, 0x4b, 0x45, 0x8d,
	0xf1, 0x1c, 0x7d, 0xfa, 0xfc, 0xe8, 0x21, 0xdc, 0xa9, 0x7e, 0x59, 0x38, 0x5b, 0xf4, 0x5f, 0xca,
	0x50, 0x24, 0xbb, 0x5e, 0xf0, 0xa6, 0x42, 0x9e, 0x60, 0x74, 0xa8, 0x25, 0x8f, 0xf5, 0xe1, 0xaa,
	0x92, 0xfb, 0xde, 0xc9, 0x8d, 0xc9, 0x16, 0x09, 0xbc, 0xff, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x47, 0x9c, 0x3b, 0xaf, 0x1c, 0x15, 0x00, 0x00,
}
