// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DeployServiceCommon.proto

package casper_v1

import (
	_ "dawn1806/rchain/api/pb/scalapb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindDeployQuery struct {
	DeployId             []byte   `protobuf:"bytes,1,opt,name=deployId,proto3" json:"deployId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindDeployQuery) Reset()         { *m = FindDeployQuery{} }
func (m *FindDeployQuery) String() string { return proto.CompactTextString(m) }
func (*FindDeployQuery) ProtoMessage()    {}
func (*FindDeployQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{0}
}

func (m *FindDeployQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDeployQuery.Unmarshal(m, b)
}
func (m *FindDeployQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDeployQuery.Marshal(b, m, deterministic)
}
func (m *FindDeployQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDeployQuery.Merge(m, src)
}
func (m *FindDeployQuery) XXX_Size() int {
	return xxx_messageInfo_FindDeployQuery.Size(m)
}
func (m *FindDeployQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDeployQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FindDeployQuery proto.InternalMessageInfo

func (m *FindDeployQuery) GetDeployId() []byte {
	if m != nil {
		return m.DeployId
	}
	return nil
}

type BlockQuery struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockQuery) Reset()         { *m = BlockQuery{} }
func (m *BlockQuery) String() string { return proto.CompactTextString(m) }
func (*BlockQuery) ProtoMessage()    {}
func (*BlockQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{1}
}

func (m *BlockQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockQuery.Unmarshal(m, b)
}
func (m *BlockQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockQuery.Marshal(b, m, deterministic)
}
func (m *BlockQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockQuery.Merge(m, src)
}
func (m *BlockQuery) XXX_Size() int {
	return xxx_messageInfo_BlockQuery.Size(m)
}
func (m *BlockQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BlockQuery proto.InternalMessageInfo

func (m *BlockQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type BlocksQuery struct {
	Depth                int32    `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksQuery) Reset()         { *m = BlocksQuery{} }
func (m *BlocksQuery) String() string { return proto.CompactTextString(m) }
func (*BlocksQuery) ProtoMessage()    {}
func (*BlocksQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{2}
}

func (m *BlocksQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksQuery.Unmarshal(m, b)
}
func (m *BlocksQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksQuery.Marshal(b, m, deterministic)
}
func (m *BlocksQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksQuery.Merge(m, src)
}
func (m *BlocksQuery) XXX_Size() int {
	return xxx_messageInfo_BlocksQuery.Size(m)
}
func (m *BlocksQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksQuery proto.InternalMessageInfo

func (m *BlocksQuery) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

type BlocksQueryByHeight struct {
	StartBlockNumber     int64    `protobuf:"varint,1,opt,name=startBlockNumber,proto3" json:"startBlockNumber,omitempty"`
	EndBlockNumber       int64    `protobuf:"varint,2,opt,name=endBlockNumber,proto3" json:"endBlockNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksQueryByHeight) Reset()         { *m = BlocksQueryByHeight{} }
func (m *BlocksQueryByHeight) String() string { return proto.CompactTextString(m) }
func (*BlocksQueryByHeight) ProtoMessage()    {}
func (*BlocksQueryByHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{3}
}

func (m *BlocksQueryByHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksQueryByHeight.Unmarshal(m, b)
}
func (m *BlocksQueryByHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksQueryByHeight.Marshal(b, m, deterministic)
}
func (m *BlocksQueryByHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksQueryByHeight.Merge(m, src)
}
func (m *BlocksQueryByHeight) XXX_Size() int {
	return xxx_messageInfo_BlocksQueryByHeight.Size(m)
}
func (m *BlocksQueryByHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksQueryByHeight.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksQueryByHeight proto.InternalMessageInfo

func (m *BlocksQueryByHeight) GetStartBlockNumber() int64 {
	if m != nil {
		return m.StartBlockNumber
	}
	return 0
}

func (m *BlocksQueryByHeight) GetEndBlockNumber() int64 {
	if m != nil {
		return m.EndBlockNumber
	}
	return 0
}

type DataAtNameQuery struct {
	Depth                int32    `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Name                 *Par     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataAtNameQuery) Reset()         { *m = DataAtNameQuery{} }
func (m *DataAtNameQuery) String() string { return proto.CompactTextString(m) }
func (*DataAtNameQuery) ProtoMessage()    {}
func (*DataAtNameQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{4}
}

func (m *DataAtNameQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAtNameQuery.Unmarshal(m, b)
}
func (m *DataAtNameQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAtNameQuery.Marshal(b, m, deterministic)
}
func (m *DataAtNameQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAtNameQuery.Merge(m, src)
}
func (m *DataAtNameQuery) XXX_Size() int {
	return xxx_messageInfo_DataAtNameQuery.Size(m)
}
func (m *DataAtNameQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAtNameQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DataAtNameQuery proto.InternalMessageInfo

func (m *DataAtNameQuery) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *DataAtNameQuery) GetName() *Par {
	if m != nil {
		return m.Name
	}
	return nil
}

type ContinuationAtNameQuery struct {
	Depth                int32    `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Names                []*Par   `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContinuationAtNameQuery) Reset()         { *m = ContinuationAtNameQuery{} }
func (m *ContinuationAtNameQuery) String() string { return proto.CompactTextString(m) }
func (*ContinuationAtNameQuery) ProtoMessage()    {}
func (*ContinuationAtNameQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{5}
}

func (m *ContinuationAtNameQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContinuationAtNameQuery.Unmarshal(m, b)
}
func (m *ContinuationAtNameQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContinuationAtNameQuery.Marshal(b, m, deterministic)
}
func (m *ContinuationAtNameQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinuationAtNameQuery.Merge(m, src)
}
func (m *ContinuationAtNameQuery) XXX_Size() int {
	return xxx_messageInfo_ContinuationAtNameQuery.Size(m)
}
func (m *ContinuationAtNameQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinuationAtNameQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ContinuationAtNameQuery proto.InternalMessageInfo

func (m *ContinuationAtNameQuery) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *ContinuationAtNameQuery) GetNames() []*Par {
	if m != nil {
		return m.Names
	}
	return nil
}

type VisualizeDagQuery struct {
	Depth                  int32    `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	ShowJustificationLines bool     `protobuf:"varint,2,opt,name=showJustificationLines,proto3" json:"showJustificationLines,omitempty"`
	StartBlockNumber       int32    `protobuf:"varint,3,opt,name=startBlockNumber,proto3" json:"startBlockNumber,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *VisualizeDagQuery) Reset()         { *m = VisualizeDagQuery{} }
func (m *VisualizeDagQuery) String() string { return proto.CompactTextString(m) }
func (*VisualizeDagQuery) ProtoMessage()    {}
func (*VisualizeDagQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{6}
}

func (m *VisualizeDagQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisualizeDagQuery.Unmarshal(m, b)
}
func (m *VisualizeDagQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisualizeDagQuery.Marshal(b, m, deterministic)
}
func (m *VisualizeDagQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisualizeDagQuery.Merge(m, src)
}
func (m *VisualizeDagQuery) XXX_Size() int {
	return xxx_messageInfo_VisualizeDagQuery.Size(m)
}
func (m *VisualizeDagQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_VisualizeDagQuery.DiscardUnknown(m)
}

var xxx_messageInfo_VisualizeDagQuery proto.InternalMessageInfo

func (m *VisualizeDagQuery) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *VisualizeDagQuery) GetShowJustificationLines() bool {
	if m != nil {
		return m.ShowJustificationLines
	}
	return false
}

func (m *VisualizeDagQuery) GetStartBlockNumber() int32 {
	if m != nil {
		return m.StartBlockNumber
	}
	return 0
}

type MachineVerifyQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MachineVerifyQuery) Reset()         { *m = MachineVerifyQuery{} }
func (m *MachineVerifyQuery) String() string { return proto.CompactTextString(m) }
func (*MachineVerifyQuery) ProtoMessage()    {}
func (*MachineVerifyQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{7}
}

func (m *MachineVerifyQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MachineVerifyQuery.Unmarshal(m, b)
}
func (m *MachineVerifyQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MachineVerifyQuery.Marshal(b, m, deterministic)
}
func (m *MachineVerifyQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MachineVerifyQuery.Merge(m, src)
}
func (m *MachineVerifyQuery) XXX_Size() int {
	return xxx_messageInfo_MachineVerifyQuery.Size(m)
}
func (m *MachineVerifyQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_MachineVerifyQuery.DiscardUnknown(m)
}

var xxx_messageInfo_MachineVerifyQuery proto.InternalMessageInfo

type PrivateNamePreviewQuery struct {
	User                 []byte   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NameQty              int32    `protobuf:"varint,3,opt,name=nameQty,proto3" json:"nameQty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateNamePreviewQuery) Reset()         { *m = PrivateNamePreviewQuery{} }
func (m *PrivateNamePreviewQuery) String() string { return proto.CompactTextString(m) }
func (*PrivateNamePreviewQuery) ProtoMessage()    {}
func (*PrivateNamePreviewQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{8}
}

func (m *PrivateNamePreviewQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateNamePreviewQuery.Unmarshal(m, b)
}
func (m *PrivateNamePreviewQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateNamePreviewQuery.Marshal(b, m, deterministic)
}
func (m *PrivateNamePreviewQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateNamePreviewQuery.Merge(m, src)
}
func (m *PrivateNamePreviewQuery) XXX_Size() int {
	return xxx_messageInfo_PrivateNamePreviewQuery.Size(m)
}
func (m *PrivateNamePreviewQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateNamePreviewQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateNamePreviewQuery proto.InternalMessageInfo

func (m *PrivateNamePreviewQuery) GetUser() []byte {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PrivateNamePreviewQuery) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PrivateNamePreviewQuery) GetNameQty() int32 {
	if m != nil {
		return m.NameQty
	}
	return 0
}

type LastFinalizedBlockQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastFinalizedBlockQuery) Reset()         { *m = LastFinalizedBlockQuery{} }
func (m *LastFinalizedBlockQuery) String() string { return proto.CompactTextString(m) }
func (*LastFinalizedBlockQuery) ProtoMessage()    {}
func (*LastFinalizedBlockQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{9}
}

func (m *LastFinalizedBlockQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastFinalizedBlockQuery.Unmarshal(m, b)
}
func (m *LastFinalizedBlockQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastFinalizedBlockQuery.Marshal(b, m, deterministic)
}
func (m *LastFinalizedBlockQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastFinalizedBlockQuery.Merge(m, src)
}
func (m *LastFinalizedBlockQuery) XXX_Size() int {
	return xxx_messageInfo_LastFinalizedBlockQuery.Size(m)
}
func (m *LastFinalizedBlockQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_LastFinalizedBlockQuery.DiscardUnknown(m)
}

var xxx_messageInfo_LastFinalizedBlockQuery proto.InternalMessageInfo

type IsFinalizedQuery struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsFinalizedQuery) Reset()         { *m = IsFinalizedQuery{} }
func (m *IsFinalizedQuery) String() string { return proto.CompactTextString(m) }
func (*IsFinalizedQuery) ProtoMessage()    {}
func (*IsFinalizedQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{10}
}

func (m *IsFinalizedQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsFinalizedQuery.Unmarshal(m, b)
}
func (m *IsFinalizedQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsFinalizedQuery.Marshal(b, m, deterministic)
}
func (m *IsFinalizedQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsFinalizedQuery.Merge(m, src)
}
func (m *IsFinalizedQuery) XXX_Size() int {
	return xxx_messageInfo_IsFinalizedQuery.Size(m)
}
func (m *IsFinalizedQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_IsFinalizedQuery.DiscardUnknown(m)
}

var xxx_messageInfo_IsFinalizedQuery proto.InternalMessageInfo

func (m *IsFinalizedQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type BondStatusQuery struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BondStatusQuery) Reset()         { *m = BondStatusQuery{} }
func (m *BondStatusQuery) String() string { return proto.CompactTextString(m) }
func (*BondStatusQuery) ProtoMessage()    {}
func (*BondStatusQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{11}
}

func (m *BondStatusQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BondStatusQuery.Unmarshal(m, b)
}
func (m *BondStatusQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BondStatusQuery.Marshal(b, m, deterministic)
}
func (m *BondStatusQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BondStatusQuery.Merge(m, src)
}
func (m *BondStatusQuery) XXX_Size() int {
	return xxx_messageInfo_BondStatusQuery.Size(m)
}
func (m *BondStatusQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BondStatusQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BondStatusQuery proto.InternalMessageInfo

func (m *BondStatusQuery) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ExploratoryDeployQuery struct {
	Term                 string   `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	UsePreStateHash      bool     `protobuf:"varint,3,opt,name=usePreStateHash,proto3" json:"usePreStateHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExploratoryDeployQuery) Reset()         { *m = ExploratoryDeployQuery{} }
func (m *ExploratoryDeployQuery) String() string { return proto.CompactTextString(m) }
func (*ExploratoryDeployQuery) ProtoMessage()    {}
func (*ExploratoryDeployQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{12}
}

func (m *ExploratoryDeployQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExploratoryDeployQuery.Unmarshal(m, b)
}
func (m *ExploratoryDeployQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExploratoryDeployQuery.Marshal(b, m, deterministic)
}
func (m *ExploratoryDeployQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExploratoryDeployQuery.Merge(m, src)
}
func (m *ExploratoryDeployQuery) XXX_Size() int {
	return xxx_messageInfo_ExploratoryDeployQuery.Size(m)
}
func (m *ExploratoryDeployQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ExploratoryDeployQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ExploratoryDeployQuery proto.InternalMessageInfo

func (m *ExploratoryDeployQuery) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *ExploratoryDeployQuery) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *ExploratoryDeployQuery) GetUsePreStateHash() bool {
	if m != nil {
		return m.UsePreStateHash
	}
	return false
}

type BondInfo struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Stake                int64    `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BondInfo) Reset()         { *m = BondInfo{} }
func (m *BondInfo) String() string { return proto.CompactTextString(m) }
func (*BondInfo) ProtoMessage()    {}
func (*BondInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{13}
}

func (m *BondInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BondInfo.Unmarshal(m, b)
}
func (m *BondInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BondInfo.Marshal(b, m, deterministic)
}
func (m *BondInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BondInfo.Merge(m, src)
}
func (m *BondInfo) XXX_Size() int {
	return xxx_messageInfo_BondInfo.Size(m)
}
func (m *BondInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BondInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BondInfo proto.InternalMessageInfo

func (m *BondInfo) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *BondInfo) GetStake() int64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

type JustificationInfo struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	LatestBlockHash      string   `protobuf:"bytes,2,opt,name=latestBlockHash,proto3" json:"latestBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JustificationInfo) Reset()         { *m = JustificationInfo{} }
func (m *JustificationInfo) String() string { return proto.CompactTextString(m) }
func (*JustificationInfo) ProtoMessage()    {}
func (*JustificationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{14}
}

func (m *JustificationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JustificationInfo.Unmarshal(m, b)
}
func (m *JustificationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JustificationInfo.Marshal(b, m, deterministic)
}
func (m *JustificationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JustificationInfo.Merge(m, src)
}
func (m *JustificationInfo) XXX_Size() int {
	return xxx_messageInfo_JustificationInfo.Size(m)
}
func (m *JustificationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JustificationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JustificationInfo proto.InternalMessageInfo

func (m *JustificationInfo) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *JustificationInfo) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

type DeployInfo struct {
	Deployer              string   `protobuf:"bytes,1,opt,name=deployer,proto3" json:"deployer,omitempty"`
	Term                  string   `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	Timestamp             int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sig                   string   `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	SigAlgorithm          string   `protobuf:"bytes,5,opt,name=sigAlgorithm,proto3" json:"sigAlgorithm,omitempty"`
	PhloPrice             int64    `protobuf:"varint,7,opt,name=phloPrice,proto3" json:"phloPrice,omitempty"`
	PhloLimit             int64    `protobuf:"varint,8,opt,name=phloLimit,proto3" json:"phloLimit,omitempty"`
	ValidAfterBlockNumber int64    `protobuf:"varint,9,opt,name=validAfterBlockNumber,proto3" json:"validAfterBlockNumber,omitempty"`
	Cost                  uint64   `protobuf:"varint,10,opt,name=cost,proto3" json:"cost,omitempty"`
	Errored               bool     `protobuf:"varint,11,opt,name=errored,proto3" json:"errored,omitempty"`
	SystemDeployError     string   `protobuf:"bytes,12,opt,name=systemDeployError,proto3" json:"systemDeployError,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DeployInfo) Reset()         { *m = DeployInfo{} }
func (m *DeployInfo) String() string { return proto.CompactTextString(m) }
func (*DeployInfo) ProtoMessage()    {}
func (*DeployInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{15}
}

func (m *DeployInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfo.Unmarshal(m, b)
}
func (m *DeployInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfo.Marshal(b, m, deterministic)
}
func (m *DeployInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfo.Merge(m, src)
}
func (m *DeployInfo) XXX_Size() int {
	return xxx_messageInfo_DeployInfo.Size(m)
}
func (m *DeployInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfo proto.InternalMessageInfo

func (m *DeployInfo) GetDeployer() string {
	if m != nil {
		return m.Deployer
	}
	return ""
}

func (m *DeployInfo) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *DeployInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DeployInfo) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func (m *DeployInfo) GetSigAlgorithm() string {
	if m != nil {
		return m.SigAlgorithm
	}
	return ""
}

func (m *DeployInfo) GetPhloPrice() int64 {
	if m != nil {
		return m.PhloPrice
	}
	return 0
}

func (m *DeployInfo) GetPhloLimit() int64 {
	if m != nil {
		return m.PhloLimit
	}
	return 0
}

func (m *DeployInfo) GetValidAfterBlockNumber() int64 {
	if m != nil {
		return m.ValidAfterBlockNumber
	}
	return 0
}

func (m *DeployInfo) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *DeployInfo) GetErrored() bool {
	if m != nil {
		return m.Errored
	}
	return false
}

func (m *DeployInfo) GetSystemDeployError() string {
	if m != nil {
		return m.SystemDeployError
	}
	return ""
}

type LightBlockInfo struct {
	// BlockMessageProto message
	BlockHash    string `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Sender       string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	SeqNum       int64  `protobuf:"varint,3,opt,name=seqNum,proto3" json:"seqNum,omitempty"`
	Sig          string `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	SigAlgorithm string `protobuf:"bytes,5,opt,name=sigAlgorithm,proto3" json:"sigAlgorithm,omitempty"`
	ShardId      string `protobuf:"bytes,6,opt,name=shardId,proto3" json:"shardId,omitempty"`
	ExtraBytes   []byte `protobuf:"bytes,7,opt,name=extraBytes,proto3" json:"extraBytes,omitempty"`
	// HeaderProto message
	Version          int64    `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp        int64    `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HeaderExtraBytes []byte   `protobuf:"bytes,10,opt,name=headerExtraBytes,proto3" json:"headerExtraBytes,omitempty"`
	ParentsHashList  []string `protobuf:"bytes,11,rep,name=parentsHashList,proto3" json:"parentsHashList,omitempty"`
	// BodyProto message
	BlockNumber    int64       `protobuf:"varint,12,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	PreStateHash   string      `protobuf:"bytes,13,opt,name=preStateHash,proto3" json:"preStateHash,omitempty"`
	PostStateHash  string      `protobuf:"bytes,14,opt,name=postStateHash,proto3" json:"postStateHash,omitempty"`
	BodyExtraBytes []byte      `protobuf:"bytes,15,opt,name=bodyExtraBytes,proto3" json:"bodyExtraBytes,omitempty"`
	Bonds          []*BondInfo `protobuf:"bytes,16,rep,name=bonds,proto3" json:"bonds,omitempty"`
	// extra
	BlockSize            string               `protobuf:"bytes,17,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	DeployCount          int32                `protobuf:"varint,18,opt,name=deployCount,proto3" json:"deployCount,omitempty"`
	FaultTolerance       float32              `protobuf:"fixed32,19,opt,name=faultTolerance,proto3" json:"faultTolerance,omitempty"`
	Justifications       []*JustificationInfo `protobuf:"bytes,20,rep,name=justifications,proto3" json:"justifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LightBlockInfo) Reset()         { *m = LightBlockInfo{} }
func (m *LightBlockInfo) String() string { return proto.CompactTextString(m) }
func (*LightBlockInfo) ProtoMessage()    {}
func (*LightBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{16}
}

func (m *LightBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightBlockInfo.Unmarshal(m, b)
}
func (m *LightBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightBlockInfo.Marshal(b, m, deterministic)
}
func (m *LightBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightBlockInfo.Merge(m, src)
}
func (m *LightBlockInfo) XXX_Size() int {
	return xxx_messageInfo_LightBlockInfo.Size(m)
}
func (m *LightBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LightBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LightBlockInfo proto.InternalMessageInfo

func (m *LightBlockInfo) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *LightBlockInfo) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *LightBlockInfo) GetSeqNum() int64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *LightBlockInfo) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func (m *LightBlockInfo) GetSigAlgorithm() string {
	if m != nil {
		return m.SigAlgorithm
	}
	return ""
}

func (m *LightBlockInfo) GetShardId() string {
	if m != nil {
		return m.ShardId
	}
	return ""
}

func (m *LightBlockInfo) GetExtraBytes() []byte {
	if m != nil {
		return m.ExtraBytes
	}
	return nil
}

func (m *LightBlockInfo) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *LightBlockInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LightBlockInfo) GetHeaderExtraBytes() []byte {
	if m != nil {
		return m.HeaderExtraBytes
	}
	return nil
}

func (m *LightBlockInfo) GetParentsHashList() []string {
	if m != nil {
		return m.ParentsHashList
	}
	return nil
}

func (m *LightBlockInfo) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *LightBlockInfo) GetPreStateHash() string {
	if m != nil {
		return m.PreStateHash
	}
	return ""
}

func (m *LightBlockInfo) GetPostStateHash() string {
	if m != nil {
		return m.PostStateHash
	}
	return ""
}

func (m *LightBlockInfo) GetBodyExtraBytes() []byte {
	if m != nil {
		return m.BodyExtraBytes
	}
	return nil
}

func (m *LightBlockInfo) GetBonds() []*BondInfo {
	if m != nil {
		return m.Bonds
	}
	return nil
}

func (m *LightBlockInfo) GetBlockSize() string {
	if m != nil {
		return m.BlockSize
	}
	return ""
}

func (m *LightBlockInfo) GetDeployCount() int32 {
	if m != nil {
		return m.DeployCount
	}
	return 0
}

func (m *LightBlockInfo) GetFaultTolerance() float32 {
	if m != nil {
		return m.FaultTolerance
	}
	return 0
}

func (m *LightBlockInfo) GetJustifications() []*JustificationInfo {
	if m != nil {
		return m.Justifications
	}
	return nil
}

// For node clients, see BlockMessage for actual Casper protocol Block representation
type BlockInfo struct {
	BlockInfo            *LightBlockInfo `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	Deploys              []*DeployInfo   `protobuf:"bytes,2,rep,name=deploys,proto3" json:"deploys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlockInfo) Reset()         { *m = BlockInfo{} }
func (m *BlockInfo) String() string { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()    {}
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{17}
}

func (m *BlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfo.Unmarshal(m, b)
}
func (m *BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfo.Marshal(b, m, deterministic)
}
func (m *BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfo.Merge(m, src)
}
func (m *BlockInfo) XXX_Size() int {
	return xxx_messageInfo_BlockInfo.Size(m)
}
func (m *BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfo proto.InternalMessageInfo

func (m *BlockInfo) GetBlockInfo() *LightBlockInfo {
	if m != nil {
		return m.BlockInfo
	}
	return nil
}

func (m *BlockInfo) GetDeploys() []*DeployInfo {
	if m != nil {
		return m.Deploys
	}
	return nil
}

type DataWithBlockInfo struct {
	PostBlockData        []*Par          `protobuf:"bytes,1,rep,name=postBlockData,proto3" json:"postBlockData,omitempty"`
	Block                *LightBlockInfo `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DataWithBlockInfo) Reset()         { *m = DataWithBlockInfo{} }
func (m *DataWithBlockInfo) String() string { return proto.CompactTextString(m) }
func (*DataWithBlockInfo) ProtoMessage()    {}
func (*DataWithBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{18}
}

func (m *DataWithBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataWithBlockInfo.Unmarshal(m, b)
}
func (m *DataWithBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataWithBlockInfo.Marshal(b, m, deterministic)
}
func (m *DataWithBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataWithBlockInfo.Merge(m, src)
}
func (m *DataWithBlockInfo) XXX_Size() int {
	return xxx_messageInfo_DataWithBlockInfo.Size(m)
}
func (m *DataWithBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DataWithBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DataWithBlockInfo proto.InternalMessageInfo

func (m *DataWithBlockInfo) GetPostBlockData() []*Par {
	if m != nil {
		return m.PostBlockData
	}
	return nil
}

func (m *DataWithBlockInfo) GetBlock() *LightBlockInfo {
	if m != nil {
		return m.Block
	}
	return nil
}

type ContinuationsWithBlockInfo struct {
	PostBlockContinuations []*WaitingContinuationInfo `protobuf:"bytes,1,rep,name=postBlockContinuations,proto3" json:"postBlockContinuations,omitempty"`
	Block                  *LightBlockInfo            `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                   `json:"-"`
	XXX_unrecognized       []byte                     `json:"-"`
	XXX_sizecache          int32                      `json:"-"`
}

func (m *ContinuationsWithBlockInfo) Reset()         { *m = ContinuationsWithBlockInfo{} }
func (m *ContinuationsWithBlockInfo) String() string { return proto.CompactTextString(m) }
func (*ContinuationsWithBlockInfo) ProtoMessage()    {}
func (*ContinuationsWithBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{19}
}

func (m *ContinuationsWithBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContinuationsWithBlockInfo.Unmarshal(m, b)
}
func (m *ContinuationsWithBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContinuationsWithBlockInfo.Marshal(b, m, deterministic)
}
func (m *ContinuationsWithBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinuationsWithBlockInfo.Merge(m, src)
}
func (m *ContinuationsWithBlockInfo) XXX_Size() int {
	return xxx_messageInfo_ContinuationsWithBlockInfo.Size(m)
}
func (m *ContinuationsWithBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinuationsWithBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContinuationsWithBlockInfo proto.InternalMessageInfo

func (m *ContinuationsWithBlockInfo) GetPostBlockContinuations() []*WaitingContinuationInfo {
	if m != nil {
		return m.PostBlockContinuations
	}
	return nil
}

func (m *ContinuationsWithBlockInfo) GetBlock() *LightBlockInfo {
	if m != nil {
		return m.Block
	}
	return nil
}

type WaitingContinuationInfo struct {
	PostBlockPatterns     []*BindPattern `protobuf:"bytes,1,rep,name=postBlockPatterns,proto3" json:"postBlockPatterns,omitempty"`
	PostBlockContinuation *Par           `protobuf:"bytes,2,opt,name=postBlockContinuation,proto3" json:"postBlockContinuation,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *WaitingContinuationInfo) Reset()         { *m = WaitingContinuationInfo{} }
func (m *WaitingContinuationInfo) String() string { return proto.CompactTextString(m) }
func (*WaitingContinuationInfo) ProtoMessage()    {}
func (*WaitingContinuationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{20}
}

func (m *WaitingContinuationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitingContinuationInfo.Unmarshal(m, b)
}
func (m *WaitingContinuationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitingContinuationInfo.Marshal(b, m, deterministic)
}
func (m *WaitingContinuationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitingContinuationInfo.Merge(m, src)
}
func (m *WaitingContinuationInfo) XXX_Size() int {
	return xxx_messageInfo_WaitingContinuationInfo.Size(m)
}
func (m *WaitingContinuationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitingContinuationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WaitingContinuationInfo proto.InternalMessageInfo

func (m *WaitingContinuationInfo) GetPostBlockPatterns() []*BindPattern {
	if m != nil {
		return m.PostBlockPatterns
	}
	return nil
}

func (m *WaitingContinuationInfo) GetPostBlockContinuation() *Par {
	if m != nil {
		return m.PostBlockContinuation
	}
	return nil
}

type ReportProduceProto struct {
	Channel              *Par               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Data                 *ListParWithRandom `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReportProduceProto) Reset()         { *m = ReportProduceProto{} }
func (m *ReportProduceProto) String() string { return proto.CompactTextString(m) }
func (*ReportProduceProto) ProtoMessage()    {}
func (*ReportProduceProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{21}
}

func (m *ReportProduceProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportProduceProto.Unmarshal(m, b)
}
func (m *ReportProduceProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportProduceProto.Marshal(b, m, deterministic)
}
func (m *ReportProduceProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportProduceProto.Merge(m, src)
}
func (m *ReportProduceProto) XXX_Size() int {
	return xxx_messageInfo_ReportProduceProto.Size(m)
}
func (m *ReportProduceProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportProduceProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReportProduceProto proto.InternalMessageInfo

func (m *ReportProduceProto) GetChannel() *Par {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *ReportProduceProto) GetData() *ListParWithRandom {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReportConsumeProto struct {
	Channels []*Par         `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	Patterns []*BindPattern `protobuf:"bytes,2,rep,name=patterns,proto3" json:"patterns,omitempty"`
	// disable because can not work and it is not important actually
	//  TaggedContinuation continuation=3;
	Peeks                []*PeekProto `protobuf:"bytes,4,rep,name=peeks,proto3" json:"peeks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReportConsumeProto) Reset()         { *m = ReportConsumeProto{} }
func (m *ReportConsumeProto) String() string { return proto.CompactTextString(m) }
func (*ReportConsumeProto) ProtoMessage()    {}
func (*ReportConsumeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{22}
}

func (m *ReportConsumeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportConsumeProto.Unmarshal(m, b)
}
func (m *ReportConsumeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportConsumeProto.Marshal(b, m, deterministic)
}
func (m *ReportConsumeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportConsumeProto.Merge(m, src)
}
func (m *ReportConsumeProto) XXX_Size() int {
	return xxx_messageInfo_ReportConsumeProto.Size(m)
}
func (m *ReportConsumeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportConsumeProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReportConsumeProto proto.InternalMessageInfo

func (m *ReportConsumeProto) GetChannels() []*Par {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *ReportConsumeProto) GetPatterns() []*BindPattern {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *ReportConsumeProto) GetPeeks() []*PeekProto {
	if m != nil {
		return m.Peeks
	}
	return nil
}

type ReportCommProto struct {
	Consume              *ReportConsumeProto   `protobuf:"bytes,1,opt,name=consume,proto3" json:"consume,omitempty"`
	Produces             []*ReportProduceProto `protobuf:"bytes,2,rep,name=produces,proto3" json:"produces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReportCommProto) Reset()         { *m = ReportCommProto{} }
func (m *ReportCommProto) String() string { return proto.CompactTextString(m) }
func (*ReportCommProto) ProtoMessage()    {}
func (*ReportCommProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{23}
}

func (m *ReportCommProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportCommProto.Unmarshal(m, b)
}
func (m *ReportCommProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportCommProto.Marshal(b, m, deterministic)
}
func (m *ReportCommProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportCommProto.Merge(m, src)
}
func (m *ReportCommProto) XXX_Size() int {
	return xxx_messageInfo_ReportCommProto.Size(m)
}
func (m *ReportCommProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportCommProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReportCommProto proto.InternalMessageInfo

func (m *ReportCommProto) GetConsume() *ReportConsumeProto {
	if m != nil {
		return m.Consume
	}
	return nil
}

func (m *ReportCommProto) GetProduces() []*ReportProduceProto {
	if m != nil {
		return m.Produces
	}
	return nil
}

type ReportProto struct {
	// Types that are valid to be assigned to Report:
	//	*ReportProto_Produce
	//	*ReportProto_Consume
	//	*ReportProto_Comm
	Report               isReportProto_Report `protobuf_oneof:"report"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReportProto) Reset()         { *m = ReportProto{} }
func (m *ReportProto) String() string { return proto.CompactTextString(m) }
func (*ReportProto) ProtoMessage()    {}
func (*ReportProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{24}
}

func (m *ReportProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportProto.Unmarshal(m, b)
}
func (m *ReportProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportProto.Marshal(b, m, deterministic)
}
func (m *ReportProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportProto.Merge(m, src)
}
func (m *ReportProto) XXX_Size() int {
	return xxx_messageInfo_ReportProto.Size(m)
}
func (m *ReportProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReportProto proto.InternalMessageInfo

type isReportProto_Report interface {
	isReportProto_Report()
}

type ReportProto_Produce struct {
	Produce *ReportProduceProto `protobuf:"bytes,1,opt,name=produce,proto3,oneof"`
}

type ReportProto_Consume struct {
	Consume *ReportConsumeProto `protobuf:"bytes,2,opt,name=consume,proto3,oneof"`
}

type ReportProto_Comm struct {
	Comm *ReportCommProto `protobuf:"bytes,3,opt,name=comm,proto3,oneof"`
}

func (*ReportProto_Produce) isReportProto_Report() {}

func (*ReportProto_Consume) isReportProto_Report() {}

func (*ReportProto_Comm) isReportProto_Report() {}

func (m *ReportProto) GetReport() isReportProto_Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *ReportProto) GetProduce() *ReportProduceProto {
	if x, ok := m.GetReport().(*ReportProto_Produce); ok {
		return x.Produce
	}
	return nil
}

func (m *ReportProto) GetConsume() *ReportConsumeProto {
	if x, ok := m.GetReport().(*ReportProto_Consume); ok {
		return x.Consume
	}
	return nil
}

func (m *ReportProto) GetComm() *ReportCommProto {
	if x, ok := m.GetReport().(*ReportProto_Comm); ok {
		return x.Comm
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReportProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReportProto_Produce)(nil),
		(*ReportProto_Consume)(nil),
		(*ReportProto_Comm)(nil),
	}
}

type SingleReport struct {
	Events               []*ReportProto `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SingleReport) Reset()         { *m = SingleReport{} }
func (m *SingleReport) String() string { return proto.CompactTextString(m) }
func (*SingleReport) ProtoMessage()    {}
func (*SingleReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{25}
}

func (m *SingleReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleReport.Unmarshal(m, b)
}
func (m *SingleReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleReport.Marshal(b, m, deterministic)
}
func (m *SingleReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleReport.Merge(m, src)
}
func (m *SingleReport) XXX_Size() int {
	return xxx_messageInfo_SingleReport.Size(m)
}
func (m *SingleReport) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleReport.DiscardUnknown(m)
}

var xxx_messageInfo_SingleReport proto.InternalMessageInfo

func (m *SingleReport) GetEvents() []*ReportProto {
	if m != nil {
		return m.Events
	}
	return nil
}

type DeployInfoWithEventData struct {
	DeployInfo           *DeployInfo     `protobuf:"bytes,1,opt,name=deployInfo,proto3" json:"deployInfo,omitempty"`
	Report               []*SingleReport `protobuf:"bytes,2,rep,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeployInfoWithEventData) Reset()         { *m = DeployInfoWithEventData{} }
func (m *DeployInfoWithEventData) String() string { return proto.CompactTextString(m) }
func (*DeployInfoWithEventData) ProtoMessage()    {}
func (*DeployInfoWithEventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{26}
}

func (m *DeployInfoWithEventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployInfoWithEventData.Unmarshal(m, b)
}
func (m *DeployInfoWithEventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployInfoWithEventData.Marshal(b, m, deterministic)
}
func (m *DeployInfoWithEventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployInfoWithEventData.Merge(m, src)
}
func (m *DeployInfoWithEventData) XXX_Size() int {
	return xxx_messageInfo_DeployInfoWithEventData.Size(m)
}
func (m *DeployInfoWithEventData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployInfoWithEventData.DiscardUnknown(m)
}

var xxx_messageInfo_DeployInfoWithEventData proto.InternalMessageInfo

func (m *DeployInfoWithEventData) GetDeployInfo() *DeployInfo {
	if m != nil {
		return m.DeployInfo
	}
	return nil
}

func (m *DeployInfoWithEventData) GetReport() []*SingleReport {
	if m != nil {
		return m.Report
	}
	return nil
}

type BlockEventInfo struct {
	BlockInfo            *LightBlockInfo            `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	Deploys              []*DeployInfoWithEventData `protobuf:"bytes,2,rep,name=deploys,proto3" json:"deploys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BlockEventInfo) Reset()         { *m = BlockEventInfo{} }
func (m *BlockEventInfo) String() string { return proto.CompactTextString(m) }
func (*BlockEventInfo) ProtoMessage()    {}
func (*BlockEventInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a733377b788abe1, []int{27}
}

func (m *BlockEventInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockEventInfo.Unmarshal(m, b)
}
func (m *BlockEventInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockEventInfo.Marshal(b, m, deterministic)
}
func (m *BlockEventInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockEventInfo.Merge(m, src)
}
func (m *BlockEventInfo) XXX_Size() int {
	return xxx_messageInfo_BlockEventInfo.Size(m)
}
func (m *BlockEventInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockEventInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockEventInfo proto.InternalMessageInfo

func (m *BlockEventInfo) GetBlockInfo() *LightBlockInfo {
	if m != nil {
		return m.BlockInfo
	}
	return nil
}

func (m *BlockEventInfo) GetDeploys() []*DeployInfoWithEventData {
	if m != nil {
		return m.Deploys
	}
	return nil
}

func init() {
	proto.RegisterType((*FindDeployQuery)(nil), "casper.FindDeployQuery")
	proto.RegisterType((*BlockQuery)(nil), "casper.BlockQuery")
	proto.RegisterType((*BlocksQuery)(nil), "casper.BlocksQuery")
	proto.RegisterType((*BlocksQueryByHeight)(nil), "casper.BlocksQueryByHeight")
	proto.RegisterType((*DataAtNameQuery)(nil), "casper.DataAtNameQuery")
	proto.RegisterType((*ContinuationAtNameQuery)(nil), "casper.ContinuationAtNameQuery")
	proto.RegisterType((*VisualizeDagQuery)(nil), "casper.VisualizeDagQuery")
	proto.RegisterType((*MachineVerifyQuery)(nil), "casper.MachineVerifyQuery")
	proto.RegisterType((*PrivateNamePreviewQuery)(nil), "casper.PrivateNamePreviewQuery")
	proto.RegisterType((*LastFinalizedBlockQuery)(nil), "casper.LastFinalizedBlockQuery")
	proto.RegisterType((*IsFinalizedQuery)(nil), "casper.IsFinalizedQuery")
	proto.RegisterType((*BondStatusQuery)(nil), "casper.BondStatusQuery")
	proto.RegisterType((*ExploratoryDeployQuery)(nil), "casper.ExploratoryDeployQuery")
	proto.RegisterType((*BondInfo)(nil), "casper.BondInfo")
	proto.RegisterType((*JustificationInfo)(nil), "casper.JustificationInfo")
	proto.RegisterType((*DeployInfo)(nil), "casper.DeployInfo")
	proto.RegisterType((*LightBlockInfo)(nil), "casper.LightBlockInfo")
	proto.RegisterType((*BlockInfo)(nil), "casper.BlockInfo")
	proto.RegisterType((*DataWithBlockInfo)(nil), "casper.DataWithBlockInfo")
	proto.RegisterType((*ContinuationsWithBlockInfo)(nil), "casper.ContinuationsWithBlockInfo")
	proto.RegisterType((*WaitingContinuationInfo)(nil), "casper.WaitingContinuationInfo")
	proto.RegisterType((*ReportProduceProto)(nil), "casper.ReportProduceProto")
	proto.RegisterType((*ReportConsumeProto)(nil), "casper.ReportConsumeProto")
	proto.RegisterType((*ReportCommProto)(nil), "casper.ReportCommProto")
	proto.RegisterType((*ReportProto)(nil), "casper.ReportProto")
	proto.RegisterType((*SingleReport)(nil), "casper.SingleReport")
	proto.RegisterType((*DeployInfoWithEventData)(nil), "casper.DeployInfoWithEventData")
	proto.RegisterType((*BlockEventInfo)(nil), "casper.BlockEventInfo")
}

func init() { proto.RegisterFile("DeployServiceCommon.proto", fileDescriptor_8a733377b788abe1) }

var fileDescriptor_8a733377b788abe1 = []byte{
	// 1436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xcf, 0x6e, 0x1b, 0xb7,
	0x13, 0xce, 0xca, 0x92, 0x2d, 0x8f, 0x14, 0x5b, 0xa6, 0xff, 0x6d, 0xfc, 0xcb, 0x2f, 0x11, 0xb6,
	0x85, 0x2b, 0xa4, 0x8e, 0x03, 0xb8, 0x41, 0x80, 0xa6, 0x40, 0x03, 0xcb, 0x71, 0x60, 0x37, 0x4e,
	0xa0, 0xac, 0x83, 0xe4, 0xd0, 0x13, 0xb5, 0x4b, 0x4b, 0xac, 0x77, 0x97, 0x5b, 0x92, 0x72, 0xa2,
	0xf4, 0xd4, 0x07, 0xe8, 0xa1, 0x97, 0x9e, 0x0b, 0xf4, 0x1d, 0xfa, 0x02, 0x7d, 0x8f, 0x1e, 0xf2,
	0x24, 0x05, 0xc9, 0xe5, 0xee, 0x4a, 0xb2, 0x93, 0xfe, 0x39, 0x79, 0xf9, 0xcd, 0xc7, 0x99, 0x8f,
	0x33, 0xc3, 0xa1, 0x0c, 0x37, 0x1e, 0x93, 0x34, 0x62, 0xe3, 0x53, 0xc2, 0x2f, 0x68, 0x40, 0x0e,
	0x58, 0x1c, 0xb3, 0x64, 0x37, 0xe5, 0x4c, 0x32, 0x34, 0x1f, 0x60, 0x91, 0x12, 0xbe, 0xb5, 0x7a,
	0xa0, 0xff, 0x3e, 0x23, 0x42, 0xe0, 0x01, 0x31, 0xc6, 0xad, 0x75, 0x11, 0xe0, 0x08, 0xa7, 0xfd,
	0x7b, 0xd9, 0xdf, 0x0c, 0x5e, 0xf2, 0x87, 0xec, 0xe5, 0x38, 0x25, 0xc2, 0xac, 0xbd, 0xbb, 0xb0,
	0xfc, 0x84, 0x26, 0xa1, 0x09, 0xf2, 0x62, 0x44, 0xf8, 0x18, 0x6d, 0x41, 0x3d, 0xd4, 0xcb, 0xe3,
	0xd0, 0x75, 0xda, 0x4e, 0xa7, 0xe9, 0xe7, 0x6b, 0xaf, 0x0d, 0xd0, 0x8d, 0x58, 0x70, 0x6e, 0x98,
	0x08, 0xaa, 0x43, 0x2c, 0x86, 0x9a, 0xb5, 0xe8, 0xeb, 0x6f, 0xef, 0x13, 0x68, 0x68, 0x86, 0x30,
	0x94, 0x35, 0xa8, 0x85, 0x24, 0x95, 0x86, 0x53, 0xf3, 0xcd, 0xc2, 0xa3, 0xb0, 0x5a, 0x22, 0x75,
	0xc7, 0x47, 0x84, 0x0e, 0x86, 0x12, 0xdd, 0x81, 0x96, 0x90, 0x98, 0x4b, 0x6d, 0x7b, 0x3e, 0x8a,
	0xfb, 0x84, 0xeb, 0x7d, 0x73, 0xfe, 0x0c, 0x8e, 0xb6, 0x61, 0x89, 0x24, 0x61, 0x99, 0x59, 0xd1,
	0xcc, 0x29, 0xd4, 0xdb, 0x87, 0xe5, 0xc7, 0x58, 0xe2, 0x7d, 0xf9, 0x1c, 0xc7, 0xe4, 0x03, 0x9a,
	0x90, 0x0b, 0xd5, 0x04, 0xc7, 0x44, 0xbb, 0x69, 0xec, 0x55, 0x77, 0x7b, 0x98, 0xfb, 0x1a, 0xf1,
	0x9e, 0xc2, 0xe6, 0x01, 0x4b, 0x24, 0x4d, 0x46, 0x58, 0x52, 0x96, 0x7c, 0xdc, 0xd5, 0x16, 0xd4,
	0xd4, 0x46, 0xe1, 0x56, 0xda, 0x73, 0xb9, 0x2f, 0x03, 0x79, 0x3f, 0x39, 0xb0, 0xf2, 0x8a, 0x8a,
	0x11, 0x8e, 0xe8, 0x3b, 0xf2, 0x18, 0x0f, 0x3e, 0xe4, 0xe7, 0x01, 0x6c, 0x88, 0x21, 0x7b, 0xf3,
	0xcd, 0x48, 0x48, 0x7a, 0x46, 0x03, 0x1d, 0xfd, 0x84, 0x26, 0xda, 0xb1, 0xd3, 0xa9, 0xfb, 0x57,
	0x58, 0x2f, 0xcd, 0xe3, 0x9c, 0x76, 0x3c, 0x83, 0x7b, 0x6b, 0x80, 0x9e, 0xe1, 0x60, 0x48, 0x13,
	0xf2, 0x8a, 0x70, 0x7a, 0x66, 0x7a, 0xc0, 0x23, 0xb0, 0xd9, 0xe3, 0xf4, 0x02, 0x4b, 0xa2, 0xce,
	0xda, 0xe3, 0xe4, 0x82, 0x92, 0x37, 0x79, 0xd1, 0x47, 0x22, 0x2b, 0x4c, 0xd3, 0xd7, 0xdf, 0xe8,
	0x26, 0x2c, 0x4a, 0x1a, 0x13, 0x21, 0x71, 0x9c, 0x66, 0x75, 0x28, 0x00, 0xe4, 0xc2, 0x82, 0x3a,
	0xfb, 0x0b, 0x39, 0xce, 0x54, 0xd8, 0xa5, 0x77, 0x03, 0x36, 0x4f, 0xb0, 0x90, 0x4f, 0x68, 0xa2,
	0xd3, 0x11, 0x16, 0xbd, 0xe5, 0x6d, 0x43, 0xeb, 0x58, 0xe4, 0x86, 0xab, 0xfb, 0xed, 0x1e, 0x2c,
	0x77, 0x59, 0x12, 0x9e, 0x4a, 0x2c, 0x47, 0x59, 0xcf, 0xdd, 0x84, 0xc5, 0x74, 0xd4, 0x8f, 0x68,
	0xf0, 0x94, 0x8c, 0x33, 0x99, 0x05, 0xe0, 0x49, 0xd8, 0x38, 0x7c, 0x9b, 0x46, 0x8c, 0x63, 0xc9,
	0xf8, 0xb8, 0xdc, 0xf8, 0x08, 0xaa, 0x92, 0xf0, 0xd8, 0xba, 0x57, 0xdf, 0xca, 0x57, 0x5f, 0x89,
	0x3a, 0x52, 0x71, 0x2b, 0xda, 0x50, 0x00, 0xa8, 0x03, 0xcb, 0x23, 0xa1, 0xd2, 0xa3, 0xc2, 0x13,
	0xcd, 0x99, 0xd3, 0x95, 0x99, 0x86, 0xbd, 0xaf, 0xa1, 0xae, 0x64, 0x1e, 0x27, 0x67, 0x4c, 0xf9,
	0xbc, 0xc0, 0x11, 0x0d, 0x95, 0x80, 0x2c, 0x58, 0x01, 0xa8, 0x56, 0x10, 0x12, 0x9f, 0x93, 0x2c,
	0x8f, 0x66, 0xe1, 0x7d, 0x0b, 0x2b, 0x13, 0x85, 0xfe, 0x1b, 0x8e, 0x3a, 0xb0, 0x1c, 0x61, 0x49,
	0x84, 0x29, 0x77, 0xe9, 0x00, 0xd3, 0xb0, 0xf7, 0x67, 0x05, 0xc0, 0x24, 0x42, 0xbb, 0xcd, 0x07,
	0x00, 0xb1, 0x5e, 0xf3, 0x75, 0x9e, 0xa3, 0xca, 0x64, 0x8e, 0x8a, 0xea, 0xcf, 0x4d, 0x57, 0xbf,
	0x05, 0x73, 0x82, 0x0e, 0xdc, 0xaa, 0xde, 0xa0, 0x3e, 0x91, 0x07, 0x4d, 0x41, 0x07, 0xfb, 0xd1,
	0x80, 0x71, 0x2a, 0x87, 0xb1, 0x5b, 0xd3, 0xa6, 0x09, 0x4c, 0xd7, 0x70, 0x18, 0xb1, 0x1e, 0xa7,
	0x01, 0x71, 0x17, 0x8c, 0xcf, 0x1c, 0xb0, 0xd6, 0x13, 0x1a, 0x53, 0xe9, 0xd6, 0x0b, 0xab, 0x06,
	0xd0, 0x7d, 0x58, 0xd7, 0x59, 0xd8, 0x3f, 0x93, 0x84, 0x97, 0xef, 0xc0, 0xa2, 0x66, 0x5e, 0x6e,
	0x54, 0x27, 0x0b, 0x98, 0x90, 0x2e, 0xb4, 0x9d, 0x4e, 0xd5, 0xd7, 0xdf, 0xaa, 0x73, 0x09, 0xe7,
	0x8c, 0x93, 0xd0, 0x6d, 0xe8, 0xba, 0xda, 0x25, 0xda, 0x81, 0x15, 0x31, 0x16, 0x92, 0xc4, 0x26,
	0x6f, 0x87, 0x0a, 0x76, 0x9b, 0xfa, 0x20, 0xb3, 0x06, 0xef, 0x8f, 0x1a, 0x2c, 0x9d, 0xa8, 0x11,
	0xa7, 0x03, 0xda, 0xda, 0x15, 0x8d, 0xe5, 0x4c, 0x37, 0xd6, 0x06, 0xcc, 0x0b, 0x92, 0x84, 0xd9,
	0x54, 0x5b, 0xf4, 0xb3, 0x95, 0xc1, 0xbf, 0x7f, 0x3e, 0x8a, 0xb3, 0x3c, 0x67, 0xab, 0x7f, 0x99,
	0x64, 0x17, 0x16, 0xc4, 0x10, 0xf3, 0xf0, 0x38, 0x74, 0xe7, 0xb5, 0xd9, 0x2e, 0xd1, 0x2d, 0x00,
	0xf2, 0x56, 0x72, 0xdc, 0x1d, 0x4b, 0x22, 0x74, 0xfe, 0x9b, 0x7e, 0x09, 0x51, 0x3b, 0x2f, 0x08,
	0x17, 0x94, 0x25, 0x59, 0xfa, 0xed, 0x72, 0xb2, 0x19, 0x16, 0xa7, 0x9b, 0xe1, 0x0e, 0xb4, 0x86,
	0x04, 0x87, 0x84, 0x1f, 0x16, 0xde, 0x41, 0x7b, 0x9f, 0xc1, 0x55, 0xff, 0xa6, 0x98, 0x93, 0x44,
	0x0a, 0x95, 0x92, 0x13, 0x2a, 0xa4, 0xdb, 0x68, 0xcf, 0xa9, 0xfe, 0x9d, 0x82, 0x51, 0x1b, 0x1a,
	0xfd, 0x52, 0x99, 0x9b, 0x3a, 0x6a, 0x19, 0x52, 0xd9, 0x48, 0xcb, 0xb7, 0xf4, 0xba, 0xc9, 0x46,
	0x19, 0x43, 0x9f, 0xc2, 0xf5, 0x94, 0x09, 0x59, 0x90, 0x96, 0x34, 0x69, 0x12, 0x54, 0xef, 0x4e,
	0x9f, 0x85, 0xe3, 0x92, 0xfe, 0x65, 0xad, 0x7f, 0x0a, 0x45, 0xdb, 0x50, 0xeb, 0xb3, 0x24, 0x14,
	0x6e, 0x4b, 0xbf, 0x01, 0xad, 0x5d, 0xf3, 0x58, 0xef, 0xda, 0x29, 0xe0, 0x1b, 0x73, 0xde, 0x07,
	0xa7, 0xf4, 0x1d, 0x71, 0x57, 0x4a, 0x7d, 0xa0, 0x00, 0x75, 0x32, 0x73, 0xf5, 0x0e, 0xd8, 0x28,
	0x91, 0x2e, 0xd2, 0xe3, 0xb3, 0x0c, 0x29, 0x3d, 0x67, 0x78, 0x14, 0xc9, 0x97, 0x2c, 0x22, 0x1c,
	0x27, 0x01, 0x71, 0x57, 0xdb, 0x4e, 0xa7, 0xe2, 0x4f, 0xa1, 0x68, 0x1f, 0x96, 0xbe, 0x2b, 0x0f,
	0x10, 0xe1, 0xae, 0x69, 0x61, 0x37, 0xac, 0xb0, 0x99, 0xf1, 0xe2, 0x4f, 0x6d, 0xf0, 0x18, 0x2c,
	0x16, 0xfd, 0x7b, 0x3f, 0xd3, 0xad, 0x16, 0xba, 0x7f, 0x1b, 0x7b, 0x1b, 0xd6, 0xd5, 0x64, 0xab,
	0xfb, 0x05, 0x11, 0xed, 0xc0, 0x82, 0x11, 0x6f, 0xdf, 0x46, 0x64, 0xf7, 0x14, 0xf3, 0xc7, 0xb7,
	0x14, 0x2f, 0x86, 0x15, 0xf5, 0x76, 0xbf, 0xa6, 0x72, 0x58, 0x04, 0xbe, 0x63, 0xca, 0xa4, 0x01,
	0x65, 0x75, 0x9d, 0xd2, 0x23, 0x3b, 0x69, 0x42, 0x3b, 0x50, 0xd3, 0xb1, 0xb3, 0x47, 0xfd, 0x2a,
	0x81, 0x86, 0xe4, 0xfd, 0xe6, 0xc0, 0x56, 0xf9, 0xa1, 0x17, 0x93, 0x81, 0x5f, 0xc3, 0x46, 0xee,
	0x7d, 0x82, 0x96, 0x29, 0xb8, 0x6d, 0xbd, 0xbf, 0xc6, 0x54, 0xd2, 0x64, 0x50, 0xe6, 0xe8, 0x30,
	0x57, 0x6c, 0xff, 0x87, 0x2a, 0x7f, 0x76, 0x60, 0xf3, 0x8a, 0x08, 0xe8, 0x21, 0xac, 0xe4, 0x31,
	0x7a, 0x58, 0x4a, 0xc2, 0x73, 0x75, 0xcd, 0xdd, 0x2e, 0x4d, 0xc2, 0x0c, 0xf4, 0x67, 0x69, 0xe8,
	0x21, 0xac, 0x5f, 0xaa, 0x6f, 0xe2, 0x07, 0xd1, 0xe5, 0x14, 0x4f, 0x00, 0xf2, 0x49, 0xca, 0xb8,
	0xec, 0x71, 0x16, 0x8e, 0x02, 0xd2, 0xd3, 0xbf, 0x4f, 0x6f, 0xc1, 0x42, 0x30, 0xc4, 0x49, 0x42,
	0xa2, 0xac, 0x41, 0x8c, 0x0f, 0x0b, 0xa2, 0x6d, 0xa8, 0x86, 0xaa, 0x80, 0x26, 0x00, 0xda, 0x55,
	0x77, 0xb9, 0x87, 0xb9, 0xca, 0xba, 0x8f, 0x93, 0x90, 0xc5, 0xbe, 0xb6, 0x3f, 0x5c, 0x7f, 0xff,
	0x08, 0x41, 0xcb, 0x04, 0x38, 0xbc, 0x20, 0x89, 0xd4, 0xee, 0xbd, 0x5f, 0x1d, 0x1b, 0xf5, 0x80,
	0x25, 0x62, 0x14, 0x67, 0x51, 0xdb, 0x50, 0xcf, 0x02, 0x88, 0x89, 0xd6, 0xc8, 0x51, 0xd4, 0x81,
	0x7a, 0x6a, 0x93, 0x53, 0xb9, 0x24, 0x39, 0xb9, 0x15, 0x7d, 0x06, 0xb5, 0x94, 0x90, 0x73, 0xe1,
	0x56, 0x35, 0x6d, 0xc5, 0x56, 0xa6, 0x47, 0xc8, 0xb9, 0x8e, 0xe6, 0x1b, 0xfb, 0x55, 0x12, 0x7f,
	0x71, 0x60, 0xd9, 0x4a, 0x8c, 0x63, 0xa3, 0xef, 0x3e, 0x2c, 0x04, 0x46, 0x6f, 0x96, 0x95, 0x2d,
	0xeb, 0x75, 0xf6, 0x30, 0xbe, 0xa5, 0xa2, 0x07, 0x50, 0x4f, 0x4d, 0x6e, 0xad, 0xe6, 0xa9, 0x6d,
	0xe5, 0xcc, 0xfb, 0x39, 0xf7, 0x2a, 0x61, 0xbf, 0x3b, 0xd0, 0xc8, 0xf7, 0x49, 0x86, 0x1e, 0xc0,
	0x42, 0xb6, 0xe5, 0x72, 0x51, 0x65, 0xef, 0x47, 0xd7, 0x7c, 0x4b, 0x56, 0xfb, 0xec, 0x61, 0x2a,
	0x1f, 0x3b, 0x8c, 0xda, 0x67, 0x8f, 0x73, 0x57, 0x3d, 0xb6, 0xb1, 0x79, 0xc5, 0x1a, 0x7b, 0x9b,
	0xd3, 0x9b, 0xb2, 0x5c, 0x1d, 0x5d, 0xf3, 0x35, 0xad, 0x5b, 0x87, 0x79, 0xae, 0x4d, 0xde, 0x57,
	0xd0, 0x3c, 0xa5, 0xc9, 0x20, 0x22, 0x86, 0x8a, 0x3e, 0x87, 0x79, 0xa2, 0x8e, 0x65, 0x6b, 0xbd,
	0x3a, 0xa3, 0x5b, 0x32, 0x3f, 0xa3, 0x78, 0x3f, 0xc0, 0x66, 0x31, 0x66, 0x54, 0x9b, 0xe9, 0x8c,
	0xe8, 0x49, 0xb1, 0x07, 0x10, 0xe6, 0xa6, 0x2c, 0x07, 0x97, 0xcd, 0xa6, 0x12, 0x0b, 0xed, 0x58,
	0x55, 0x59, 0x45, 0xd6, 0x2c, 0xbf, 0xac, 0xd0, 0xb7, 0xca, 0x7f, 0x74, 0x60, 0x49, 0xdf, 0x1c,
	0x1d, 0xf4, 0x3f, 0xcc, 0xd0, 0x2f, 0xa7, 0x67, 0xe8, 0xed, 0x59, 0x9d, 0x13, 0x87, 0xcb, 0x07,
	0x6a, 0xf7, 0xf0, 0xfd, 0xa3, 0x2e, 0xfc, 0x2f, 0x60, 0x2c, 0xdd, 0xe5, 0xc1, 0x10, 0xd3, 0xc4,
	0xee, 0xd4, 0xff, 0x0c, 0x06, 0x2c, 0x6a, 0x39, 0xde, 0xff, 0x05, 0xc1, 0x11, 0x09, 0xdb, 0x92,
	0x63, 0x2a, 0xdb, 0xd3, 0x9d, 0xd3, 0x71, 0x8e, 0xae, 0xf5, 0xe7, 0x35, 0xfd, 0x8b, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x37, 0xa0, 0x34, 0x9c, 0x0e, 0x00, 0x00,
}
